[package]
name = "wave-application-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nudox-compile-vocab = { path = "../../../compiler/crates/nudox-compile-vocab" }
serde_json.workspace = true
wave-application-core = { path = "../wave-application-core" }

[lints]
workspace = true
