[package]
name = "wave-application-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.nudox]
role = "adapter"

[dependencies]
nudox-adaptive = { path = "../nudox-adaptive" }
nudox-id = { path = "../nudox-id" }
nudox-compile-vocab = { path = "../nudox-compile-vocab" }
serde.workspace = true
serde_json.workspace = true
wave-application-core = { path = "../wave-application-core" }

[dev-dependencies]
thiserror.workspace = true

[lints.rust]
unsafe_code = "deny"
unused_lifetimes = "warn"
unused_qualifications = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
dbg_macro = "deny"
exit = "deny"
mem_forget = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
