//! Frozen package/project coordinates copied from the committed driver lanes.
//!
//! This file owns only corpus membership.  Resolution, source-byte binding,
//! and typed unavailable terminals live in the parent inventory module.

use super::*;

pub(super) const RUST_PACKAGES: [PackageCoordinate; REAL_CASES_PER_LANE] = [
    PackageCoordinate::Purl("cargo:serde@1.0.229"),
    PackageCoordinate::Purl("cargo:thiserror@2.0.20"),
    PackageCoordinate::Purl("cargo:ab_glyph@0.2.32"),
    PackageCoordinate::Purl("cargo:block2@0.6.2"),
    PackageCoordinate::Purl("cargo:cookie_store@0.7.0"),
    PackageCoordinate::Purl("cargo:dragonbox_ecma@0.1.12"),
    PackageCoordinate::Purl("cargo:futures-executor@0.3.34"),
    PackageCoordinate::Purl("cargo:hashbrown@0.14.5"),
    PackageCoordinate::Purl("cargo:jni-sys-macros@0.4.1"),
    PackageCoordinate::Purl("cargo:ndk-context@0.1.1"),
    PackageCoordinate::Purl("cargo:ownedbytes@0.9.0"),
    PackageCoordinate::Purl("cargo:proptest@1.11.0"),
    PackageCoordinate::Purl("cargo:rayon@1.11.0"),
    PackageCoordinate::Purl("cargo:semver-parser@0.7.0"),
    PackageCoordinate::Purl("cargo:tantivy@0.25.0"),
    PackageCoordinate::Purl("cargo:typed-arena@2.0.2"),
    PackageCoordinate::Purl("cargo:wasmtime-internal-versioned-export-macros@47.0.3"),
    PackageCoordinate::Purl("cargo:windows_x86_64_gnullvm@0.48.5"),
    // `compiler-ir-vocabulary` and `compiler-ir` both folded into
    // `backend-semantic`; `backend-version` keeps the two frozen workspace
    // coordinates distinct while naming a real current package.
    PackageCoordinate::Purl("cargo:backend-semantic@0.1.0"),
    PackageCoordinate::Purl("cargo:backend-version@0.1.0"),
];

pub(super) const TYPESCRIPT_PACKAGES: [PackageCoordinate; REAL_CASES_PER_LANE] = [
    PackageCoordinate::Purl("npm:lodash@4.17.21"),
    PackageCoordinate::Purl("npm:zod@3.25.76"),
    PackageCoordinate::Purl("npm:@types/react@18.3.12"),
    PackageCoordinate::Purl("npm:@babel/parser@7.26.8"),
    PackageCoordinate::Purl("npm:typescript@5.7.2"),
    PackageCoordinate::Purl("npm:react@18.3.1"),
    PackageCoordinate::Purl("npm:express@4.21.1"),
    PackageCoordinate::Purl("npm:@types/node@22.10.1"),
    PackageCoordinate::Purl("npm:date-fns@4.1.0"),
    PackageCoordinate::Purl("npm:axios@1.7.9"),
    PackageCoordinate::Purl("npm:chalk@5.3.0"),
    PackageCoordinate::Purl("npm:commander@13.1.0"),
    PackageCoordinate::Purl("npm:fastify@5.2.1"),
    PackageCoordinate::Purl("npm:uuid@11.0.3"),
    PackageCoordinate::Purl("npm:pino@9.6.0"),
    PackageCoordinate::Purl("npm:hono@4.6.12"),
    PackageCoordinate::Purl("npm:yup@1.6.1"),
    PackageCoordinate::Purl("npm:rxjs@7.8.1"),
    PackageCoordinate::Purl("npm:@tanstack/query-core@5.62.8"),
    PackageCoordinate::Purl("npm:eslint@9.17.0"),
];

pub(super) const PYTHON_PACKAGES: [PackageCoordinate; REAL_CASES_PER_LANE] = [
    PackageCoordinate::Purl("pypi:requests@2.32.3"),
    PackageCoordinate::Purl("pypi:attrs@25.3.0"),
    PackageCoordinate::Purl("pypi:flask@3.1.1"),
    PackageCoordinate::Purl("pypi:six@1.17.0"),
    PackageCoordinate::Purl("pypi:wcwidth@0.2.13"),
    PackageCoordinate::Purl("pypi:idna@3.10"),
    PackageCoordinate::Purl("pypi:certifi@2025.7.14"),
    PackageCoordinate::Purl("pypi:packaging@25.0"),
    PackageCoordinate::Purl("pypi:pyparsing@3.2.3"),
    PackageCoordinate::Purl("pypi:iniconfig@2.1.0"),
    PackageCoordinate::Purl("pypi:pluggy@1.6.0"),
    PackageCoordinate::Purl("pypi:click@8.2.1"),
    PackageCoordinate::Purl("pypi:itsdangerous@2.2.0"),
    PackageCoordinate::Purl("pypi:jinja2@3.1.6"),
    PackageCoordinate::Purl("pypi:markupsafe@3.0.2"),
    PackageCoordinate::Purl("pypi:werkzeug@3.1.3"),
    PackageCoordinate::Purl("pypi:colorama@0.4.6"),
    PackageCoordinate::Purl("pypi:PyYAML@6.0.2"),
    PackageCoordinate::Purl("pypi:tomli@2.2.1"),
    PackageCoordinate::Purl("pypi:webencodings@0.5.1"),
];

pub(super) const GO_PACKAGES: [PackageCoordinate; GO_CASES_PER_LANE] = [
    PackageCoordinate::Purl("golang:github.com/google/uuid@v1.6.0"),
    PackageCoordinate::Purl("golang:gopkg.in/yaml.v3@v3.0.1"),
    PackageCoordinate::Purl("golang:github.com/gorilla/mux@v1.8.1"),
    PackageCoordinate::Purl("golang:github.com/google/go-cmp@v0.6.0"),
    PackageCoordinate::Purl("golang:golang.org/x/sync@v0.10.0"),
    PackageCoordinate::Purl("golang:golang.org/x/mod@v0.17.0"),
    PackageCoordinate::Purl("golang:golang.org/x/time@v0.5.0"),
    PackageCoordinate::Purl("golang:golang.org/x/tools@v0.30.0"),
    PackageCoordinate::Purl("golang:github.com/pelletier/go-toml/v2@v2.2.2"),
    PackageCoordinate::Purl("golang:github.com/oklog/ulid/v2@v2.1.0"),
    PackageCoordinate::Purl("golang:github.com/cespare/xxhash/v2@v2.3.0"),
    PackageCoordinate::Purl("golang:github.com/BurntSushi/toml@v1.4.0"),
    PackageCoordinate::Purl("golang:github.com/zeebo/xxh3@v1.0.2"),
    PackageCoordinate::Purl("golang:github.com/minio/highwayhash@v1.0.2"),
    PackageCoordinate::Purl("golang:github.com/julienschmidt/httprouter@v1.3.0"),
    PackageCoordinate::Purl("golang:github.com/go-chi/chi/v5@v5.0.12"),
    PackageCoordinate::Purl("golang:github.com/rs/zerolog@v1.33.0"),
    PackageCoordinate::Purl("golang:github.com/davecgh/go-spew@v1.1.1"),
    PackageCoordinate::Purl("golang:github.com/pkg/errors@v0.9.1"),
    PackageCoordinate::Purl("golang:github.com/mitchellh/go-homedir@v1.1.0"),
    PackageCoordinate::Purl("golang:rsc.io/quote@v1.5.2"),
];

pub(super) const JAVA_PACKAGES: [PackageCoordinate; REAL_CASES_PER_LANE] = [
    PackageCoordinate::Purl("maven:org.apache.commons:commons-lang3@3.14.0"),
    PackageCoordinate::Purl("maven:com.google.guava:guava@33.0.0-jre"),
    PackageCoordinate::Purl("maven:com.fasterxml.jackson.core:jackson-databind@2.16.1"),
    PackageCoordinate::Purl("maven:org.junit.jupiter:junit-jupiter-api@5.10.1"),
    PackageCoordinate::Purl("maven:io.projectreactor:reactor-core@3.6.2"),
    PackageCoordinate::Purl("maven:org.apache.commons:commons-csv@1.10.0"),
    PackageCoordinate::Purl("maven:org.jsoup:jsoup@1.17.2"),
    PackageCoordinate::Purl("maven:org.ow2.asm:asm@9.6"),
    PackageCoordinate::Purl("maven:com.google.code.gson:gson@2.10.1"),
    PackageCoordinate::Purl("maven:io.vavr:vavr@0.10.4"),
    PackageCoordinate::Purl("maven:org.jctools:jctools-core@4.0.2"),
    PackageCoordinate::Purl("maven:org.apache.commons:commons-math3@3.6.1"),
    PackageCoordinate::Purl("maven:org.eclipse.collections:eclipse-collections@11.1.0"),
    PackageCoordinate::Purl("maven:org.bitbucket.b_c:jose4j@0.9.6"),
    PackageCoordinate::Purl("maven:org.tukaani:xz@1.9"),
    PackageCoordinate::Purl("maven:org.apache.commons:commons-compress@1.26.0"),
    PackageCoordinate::Purl("maven:org.apache.commons:commons-pool2@2.12.0"),
    PackageCoordinate::Purl("maven:org.jetbrains:annotations@24.0.1"),
    PackageCoordinate::Purl("maven:com.zaxxer:HikariCP@5.1.0"),
    PackageCoordinate::Purl("maven:org.apache.commons:commons-text@1.11.0"),
];

pub(super) const CSHARP_PACKAGES: [PackageCoordinate; REAL_CASES_PER_LANE] = [
    PackageCoordinate::Purl("nuget:nullable@1.3.1"),
    PackageCoordinate::Purl("nuget:xunit.assert.source@2.9.3"),
    PackageCoordinate::Purl("nuget:isexternalinit@1.0.3"),
    PackageCoordinate::Purl("nuget:polyfill@2.0.0"),
    PackageCoordinate::Purl("nuget:devlooped.tablestorage.source@5.5.0"),
    PackageCoordinate::Purl("nuget:tinyioc@1.4.0-rc1"),
    PackageCoordinate::Purl("nuget:ramltoopenapiconverter.sourceonly@0.21.0"),
    PackageCoordinate::Purl("nuget:ramltoopenapiconverter.sourceonly@0.8.0"),
    PackageCoordinate::Purl("nuget:esp-net-source@0.6.4"),
    PackageCoordinate::Purl("nuget:esp-net-source@0.2.3"),
    PackageCoordinate::Purl("nuget:nullability.source@2.3.0"),
    PackageCoordinate::Purl("nuget:nullability.source@2.1.0"),
    PackageCoordinate::Purl("nuget:morelinq.source.moreenumerable.distinctby@1.0.2"),
    PackageCoordinate::Purl("nuget:morelinq.source.moreenumerable.pairwise@1.0.2"),
    PackageCoordinate::Purl("nuget:morelinq.source.moreenumerable.acquire@1.0.2"),
    PackageCoordinate::Purl("nuget:morelinq.source.moreenumerable.assertcount@1.0.2"),
    PackageCoordinate::Purl("nuget:morelinq.source.moreenumerable.batch@1.0.2"),
    PackageCoordinate::Purl("nuget:morelinq.source.moreenumerable.generate@1.0.2"),
    PackageCoordinate::Purl("nuget:morelinq.source.moreenumerable.generatebyindex@1.0.2"),
    PackageCoordinate::Purl("nuget:tinyioc@1.3.0"),
];

pub(super) const CLANG_PROJECTS: [PackageCoordinate; REAL_CASES_PER_LANE] = [
    PackageCoordinate::Project("stb"),
    PackageCoordinate::Project("sqlite-amalgamation"),
    PackageCoordinate::Project("redis"),
    PackageCoordinate::Project("lua"),
    PackageCoordinate::Project("json-c"),
    PackageCoordinate::Project("yaml-cpp"),
    PackageCoordinate::Project("kilo"),
    PackageCoordinate::Project("zlib"),
    PackageCoordinate::Project("Vulkan-Headers"),
    PackageCoordinate::Project("buck2-with-prelude"),
    PackageCoordinate::Project("klib"),
    PackageCoordinate::Project("miniaudio"),
    PackageCoordinate::Project("vurtun-lib"),
    PackageCoordinate::Project("rxi-map"),
    PackageCoordinate::Project("q3vm"),
    PackageCoordinate::Project("STC"),
    PackageCoordinate::Project("pugixml"),
    PackageCoordinate::Project("cJSON"),
    PackageCoordinate::Project("nng"),
    PackageCoordinate::Project("Unity"),
];
