[package]
name = "nudox-ir-format"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nudox-compile-vocab = { path = "../nudox-compile-vocab" }
nudox-id = { path = "../nudox-id" }
nudox-ir-vocab = { path = "../nudox-ir-vocab" }
thiserror.workspace = true

[lib]
path = "src/lib.rs"
