[package]
name = "wave-application-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.nudox]
role = "adapter"

[[bin]]
name = "wave-application-cli"
path = "src/main.rs"

[dependencies]
wave-application-core = { path = "../wave-application-core" }
wave-application-protocol = { path = "../wave-application-protocol" }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
