//! Pinned from the v6 board's path scan (`Nudox-Design-System/v6/moments/data/sym_uses.json`, `serde_json@1.0.151` `from_str`): real lines from this repository's own crates.
//! Generated by `.local/lanes/wave6/glyph/gen_reach.py`; the counts are the scan's (a path scan, not a compiler).

use crate::anatomy::plan::Effect;
use crate::anatomy::reach::{Basis, CrateUse, Line, Reach, Reached};

const NAME: &str = "from_str";

pub(crate) fn serde_json_from_str() -> Reach {
    let line = |file: &str, line: u32, text: &str, member: Option<&str>| {
        let mark = text.find(NAME).and_then(|at| {
            u32::try_from(at)
                .ok()
                .zip(u32::try_from(at + NAME.len()).ok())
        });
        Line {
            file: file.to_owned(),
            line,
            text: text.to_owned(),
            mark,
            member: member.map(ToOwned::to_owned),
            ..Line::default()
        }
    };
    let mut yours = Vec::new();
    yours.push(CrateUse {
        name: "journeys".to_owned(),
        count: 13,
        members: vec![],
        lines: vec![
            line(
                "tests/cluster_source_journey.rs",
                754,
                ".filter_map(|line| serde_json::from_str::<Value>(&line).ok())",
                None,
            ),
            line(
                "tests/cutover_e2e.rs",
                3068,
                "serde_json::from_str::<serde_json::Value>(line)",
                None,
            ),
            line(
                "tests/index_tentpole.rs",
                316,
                ".filter_map(|line| serde_json::from_str::<Value>(&line).ok())",
                None,
            ),
            line(
                "tests/live_registry.rs",
                366,
                "serde_json::from_str(include_str!(\"../../../.config/nix/corpus-pins.json\"))",
                None,
            ),
            line(
                "tests/new_user_forge.rs",
                417,
                ".filter_map(|line| serde_json::from_str::<Value>(line).ok())",
                None,
            ),
            line(
                "tests/new_user_graph_journey.rs",
                229,
                ".filter_map(|line| serde_json::from_str::<Value>(line).ok())",
                None,
            ),
            line(
                "tests/package_journeys.rs",
                549,
                ".filter_map(|line| serde_json::from_str::<Value>(line).ok())",
                None,
            ),
        ],
    });
    yours.push(CrateUse {
        name: "workspace".to_owned(),
        count: 11,
        members: vec![],
        lines: vec![
            line("src/dag.rs", 59, "serde_json::from_str(json).map_err(|error| format!(\"malformed package DAG: {error}\"))?;", None),
            line("src/lib.rs", 399, "let metadata: Metadata = serde_json::from_str(json)", None),
            line("src/quality/evidence.rs", 16, "let root: Value = match serde_json::from_str(canonical) {", None),
            line("src/quality/evidence.rs", 85, "let value: Value = match serde_json::from_str(&projection.contents) {", None),
            line("src/quality/evidence.rs", 173, "let value: Value = match serde_json::from_str(&source.contents) {", None),
            line("src/quality/source/ownership.rs", 18, "let policy: CanonicalOwnershipPolicy = match serde_json::from_str(&policy_source.contents) {", None),
            line("src/quality/structure.rs", 19, "let policy: ModuleStructurePolicy = match serde_json::from_str(&policy_source.contents) {", None),
        ],
    });
    yours.push(CrateUse {
        name: "library".to_owned(),
        count: 6,
        members: vec![],
        lines: vec![
            line("tests/index_source_span.rs", 83, "assert!(serde_json::from_str::<UntrustedSourceSpan>(&oversized_path_json).is_err());", None),
            line("tests/index_source_span.rs", 89, "assert!(serde_json::from_str::<UntrustedSourceSpan>(&oversized_snapshot_json).is_err());", None),
            line("wire/tests.rs", 214, "assert!(serde_json::from_str::<EventDto>(&encoded).is_err());", None),
            line("wire/tests.rs", 217, "let mut forged: serde_json::Value = serde_json::from_str(&encoded).expect(\"value\");", None),
            line("wire/tests.rs", 229, "let mut forged_scope: serde_json::Value = serde_json::from_str(&encoded).expect(\"value\");", None),
        ],
    });
    yours.push(CrateUse {
        name: "control".to_owned(),
        count: 4,
        members: vec![],
        lines: vec![
            line("src/cli/evidence.rs", 93, "let request = serde_json::from_str::<CandidateRequest>(&input::request_json(arguments)?)", None),
            line("src/cli/evidence.rs", 105, "let request = serde_json::from_str::<EvaluationRequest>(&input::request_json(arguments)?)", None),
            line("src/cli/evidence.rs", 120, "let request = serde_json::from_str::<DecisionRequest>(&input::request_json(arguments)?)", None),
            line("src/wire.rs", 79, "let request = serde_json::from_str::<Self>(json)", None),
        ],
    });
    yours.push(CrateUse {
        name: "extension-qdrant".to_owned(),
        count: 4,
        members: vec![],
        lines: vec![
            line("src/http.rs", 945, "serde_json::from_str(body).map_err(HttpProviderError::Decode)", None),
            line("src/http/tests.rs", 297, "let decoded: PointPayload = serde_json::from_str(&encoded).expect(\"decode payload\");", None),
            line("src/http/tests.rs", 309, "let legacy_payload: PointPayload = serde_json::from_str(legacy).expect(\"legacy payload\");", None),
            line("src/server/wire/response.rs", 30, "serde_json::from_str(body).map_err(|source| QdrantError::Decode { phase, source })", None),
        ],
    });
    yours.push(CrateUse {
        name: "performance-tests".to_owned(),
        count: 4,
        members: vec![],
        lines: vec![
            line(
                "src/bin/integrated.rs",
                2419,
                "exact_wire_match &= serde_json::from_str::<serde_json::Value>(&cli_json)?",
                None,
            ),
            line(
                "src/bin/integrated.rs",
                2420,
                "== serde_json::from_str::<serde_json::Value>(&mcp_json)?;",
                None,
            ),
            line(
                "src/bin/integrated.rs",
                2505,
                "let Ok(manifest) = serde_json::from_str::<serde_json::Value>(&text) else {",
                None,
            ),
        ],
    });
    yours.push(CrateUse {
        name: "facet".to_owned(),
        count: 3,
        members: vec![],
        lines: vec![
            line("src/graph/gallery.rs", 508, "let p: Proto = serde_json::from_str(json).ok()?;", None),
            line("src/marks/fixture.rs", 29, "LazyLock::new(|| serde_json::from_str(JSON).unwrap_or_else(|error| panic!(\"marks fixture.json: {error}\")));", None),
            line("src/semantics/tests/recipes.rs", 123, "let want: serde_json::Value = serde_json::from_str(json).expect(\"golden json\");", None),
        ],
    });
    yours.push(CrateUse {
        name: "local-service".to_owned(),
        count: 3,
        members: vec![],
        lines: vec![
            line(
                "src/builtin/discovery_search.rs",
                5524,
                "assert!(serde_json::from_str::<SearchContinuation>(&encoded).is_err());",
                None,
            ),
            line(
                "src/builtin/discovery_search/benchmark.rs",
                641,
                "let response = match serde_json::from_str::<Value>(&line) {",
                None,
            ),
            line(
                "src/builtin/discovery_search/benchmark.rs",
                719,
                "let response = match serde_json::from_str::<Value>(&line) {",
                None,
            ),
        ],
    });
    yours.push(CrateUse {
        name: "present".to_owned(),
        count: 3,
        members: vec![],
        lines: vec![
            line("budget.rs", 752, "let fixture: Value = serde_json::from_str(include_str!(\"fixtures/payload-budgets.json\"))", None),
            line("budget.rs", 858, "let fixture: Value = serde_json::from_str(include_str!(\"fixtures/payload-budgets.json\"))", None),
            line("call.rs", 357, "let command = serde_json::from_str::<SurfaceCommand>(encoded).map_err(|error| {", None),
        ],
    });
    yours.push(CrateUse {
        name: "engine".to_owned(),
        count: 2,
        members: vec![],
        lines: vec![
            line("src/registry/ecosystem_decoders.rs", 237, "let row: Value = serde_json::from_str(line).map_err(|_| TransportFailure::Protocol)?;", None),
            line("tests/impact_use_case.rs", 263, "let stored: StoredBenchReport = serde_json::from_str(&body).map_err(|error| {", None),
        ],
    });
    yours.push(CrateUse {
        name: "gui-harness".to_owned(),
        count: 2,
        members: vec![],
        lines: vec![
            line(
                "src/design_contract.rs",
                477,
                "let props: serde_json::Value = serde_json::from_str(&html[start..end]).ok()?;",
                None,
            ),
            line(
                "src/input.rs",
                977,
                "serde_json::from_str::<InputStep>(&encoded),",
                None,
            ),
        ],
    });
    yours.push(CrateUse {
        name: "cli".to_owned(),
        count: 1,
        members: vec![],
        lines: vec![line(
            "src/tests.rs",
            674,
            "let value: serde_json::Value = serde_json::from_str(&json).expect(\"typed DTO\");",
            None,
        )],
    });
    yours.push(CrateUse {
        name: "desktop".to_owned(),
        count: 1,
        members: vec![],
        lines: vec![
            line("src/runtime/snapshot_tests.rs", 36, "serde_json::from_str(&format!(\"[{}]\", vec![byte.to_string(); 32].join(\",\"))).expect(\"row key\")", None),
        ],
    });
    yours.push(CrateUse {
        name: "frontend-clang".to_owned(),
        count: 1,
        members: vec![],
        lines: vec![line(
            "compile_commands.rs",
            90,
            "let entries: Vec<RawEntry> = serde_json::from_str(&text).ok()?;",
            None,
        )],
    });
    yours.push(CrateUse {
        name: "semantic".to_owned(),
        count: 1,
        members: vec![],
        lines: vec![
            line("tests/vocabulary_package_urls.rs", 84, "let reopened: PackageUrl = serde_json::from_str(&wire).expect(\"reopen package URL\");", None),
        ],
    });
    Reach {
        yours,
        basis: Basis::Scanned,
        note: Some("A path scan of your crates: real lines, approximate counts.".to_owned()),
        ..Reach::default()
    }
}
