//! Pinned from the v6 board's path scan (`Nudox-Design-System/v6/moments/data/sym_uses.json`, `serde@1.0.229` `Serialize`): real lines from this repository's own crates.
//! Generated by `.local/lanes/wave6/glyph/gen_reach.py`; the counts are the scan's (a path scan, not a compiler).

use crate::anatomy::reach::{Basis, CrateUse, Line, Reach, Reached};
use crate::anatomy::plan::Effect;

const NAME: &str = "Serialize";

pub(crate) fn serde_serialize() -> Reach {
    let line = |file: &str, line: u32, text: &str, member: Option<&str>| {
        let mark = text.find(NAME).and_then(|at| u32::try_from(at).ok().zip(u32::try_from(at + NAME.len()).ok()));
        Line { file: file.to_owned(), line, text: text.to_owned(), mark, member: member.map(ToOwned::to_owned), ..Line::default() }
    };
    let mut yours = Vec::new();
    yours.push(CrateUse {
        name: "desktop".to_owned(),
        count: 66,
        members: vec![],
        lines: vec![
            line("src/model/local_package/readme.rs", 16, "#[derive(Clone, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]", None),
            line("src/model/pages/common.rs", 14, "#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, serde::Serialize, serde::Deserialize)]", None),
            line("src/model/pages/common.rs", 94, "#[derive(Clone, Copy, Eq, Hash, Ord, PartialEq, PartialOrd, serde::Serialize, serde::Deserialize)]", None),
            line("src/model/pages/common.rs", 111, "#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, serde::Serialize, serde::Deserialize)]", None),
            line("src/model/pages/orbit.rs", 8, "#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, serde::Serialize, serde::Deserialize)]", None),
            line("src/model/pages/orbit.rs", 19, "#[derive(Clone, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]", None),
            line("src/model/pages/orbit.rs", 30, "#[derive(Clone, Debug, Eq, PartialEq, serde::Serialize, serde::Deserialize)]", None),
        ],
    });
    yours.push(CrateUse {
        name: "library".to_owned(),
        count: 43,
        members: vec![],
        lines: vec![
            line("browse/roles.rs", 12, "use serde::{Deserialize, Serialize};", None),
            line("browse/tree.rs", 8, "use serde::{Deserialize, Serialize};", None),
            line("command.rs", 9, "use serde::{Deserialize, Serialize};", None),
            line("forge_identity.rs", 1, "use serde::{Deserialize, Serialize};", None),
            line("package_graph.rs", 11, "use serde::{Deserialize, Serialize};", None),
            line("protocol/field.rs", 8, "use serde::Serialize;", None),
            line("protocol/index.rs", 10, "use serde::{", None),
        ],
    });
    yours.push(CrateUse {
        name: "extension-qdrant".to_owned(),
        count: 12,
        members: vec![],
        lines: vec![
            line("src/http.rs", 13, "use serde::{Deserialize, Serialize};", None),
            line("src/server/adapter.rs", 6, "use serde::Serialize;", None),
            line("src/server/contract.rs", 13, "use serde::Serialize;", None),
            line("src/server/transport.rs", 8, "use serde::Serialize;", None),
            line("src/server/wire/request.rs", 9, "use serde::{", None),
            line("src/server/wire/request.rs", 28, "#[derive(Clone, Copy, Debug, serde::Deserialize, Eq, PartialEq, serde::Serialize)]", None),
            line("src/server/wire/request.rs", 55, "#[derive(Clone, Copy, Debug, serde::Deserialize, Eq, PartialEq, serde::Serialize)]", None),
        ],
    });
    yours.push(CrateUse {
        name: "gui-harness".to_owned(),
        count: 10,
        members: vec![],
        lines: vec![
            line("src/artifact.rs", 6, "use serde::{Deserialize, Serialize};", None),
            line("src/conformance.rs", 15, "use serde::{Deserialize, Serialize};", None),
            line("src/design_contract.rs", 12, "use serde::{Deserialize, Serialize};", None),
            line("src/diff.rs", 4, "use serde::{Deserialize, Serialize};", None),
            line("src/input.rs", 4, "use serde::{Deserialize, Serialize};", None),
            line("src/journey.rs", 8, "use serde::{Deserialize, Serialize};", None),
            line("src/lib.rs", 26, "use serde::{Deserialize, Serialize};", None),
        ],
    });
    yours.push(CrateUse {
        name: "advisory".to_owned(),
        count: 5,
        members: vec![],
        lines: vec![
            line("src/authority.rs", 18, "use serde::{Deserialize, Serialize};", None),
            line("src/journal.rs", 3, "use serde::{Deserialize, Serialize};", None),
            line("src/model.rs", 6, "use serde::{Deserialize, Serialize};", None),
            line("src/policy.rs", 1, "use serde::{Deserialize, Serialize};", None),
            line("src/wire.rs", 1, "use serde::{Deserialize, Serialize};", None),
        ],
    });
    yours.push(CrateUse {
        name: "engine".to_owned(),
        count: 4,
        members: vec![],
        lines: vec![
            line("src/forge/mod.rs", 30, "use serde::{Deserialize, Serialize};", None),
            line("src/registry/discovery.rs", 10, "use serde::{Deserialize, Serialize};", None),
            line("src/registry/wire.rs", 377, "fn put_json<T: serde::Serialize>(out: &mut Vec<u8>, value: &T) {", None),
            line("tests/use_case_support/mod.rs", 14, "use serde::Serialize;", None),
        ],
    });
    yours.push(CrateUse {
        name: "local-service".to_owned(),
        count: 4,
        members: vec![],
        lines: vec![
            line("src/builtin/discovery_search.rs", 13, "use serde::{Deserialize, Serialize};", None),
            line("src/builtin/product_state.rs", 37, "use serde::{Deserialize, Serialize};", None),
            line("src/discovery.rs", 23, "use serde::{Deserialize, Serialize};", None),
            line("src/query/remote.rs", 13, "use serde::{Deserialize, Serialize};", None),
        ],
    });
    yours.push(CrateUse {
        name: "cluster-transport".to_owned(),
        count: 3,
        members: vec![],
        lines: vec![
            line("src/control.rs", 7, "use serde::{Deserialize, Serialize};", None),
            line("src/lib.rs", 45, "use serde::{Deserialize, Deserializer, Serialize, de::DeserializeOwned};", None),
            line("src/probe.rs", 14, "use serde::{Deserialize, Serialize, de::DeserializeOwned};", None),
        ],
    });
    yours.push(CrateUse {
        name: "store".to_owned(),
        count: 3,
        members: vec![],
        lines: vec![
            line("benches/capacity_planning/model.rs", 6, "use serde::Serialize;", None),
            line("examples/capacity_worksheet/capacity/input.rs", 6, "use serde::{Deserialize, Serialize};", None),
            line("examples/capacity_worksheet/capacity/output.rs", 6, "use serde::Serialize;", None),
        ],
    });
    yours.push(CrateUse {
        name: "mcp".to_owned(),
        count: 2,
        members: vec![],
        lines: vec![
            line("src/jsonrpc.rs", 32, "use serde::{", None),
            line("src/jsonrpc/resources.rs", 21, "use serde::Serialize;", None),
        ],
    });
    yours.push(CrateUse {
        name: "present".to_owned(),
        count: 2,
        members: vec![],
        lines: vec![
            line("budget.rs", 8, "use serde::Serialize;", None),
            line("dto.rs", 12, "use serde::{Deserialize, Serialize};", None),
        ],
    });
    yours.push(CrateUse {
        name: "semantic".to_owned(),
        count: 2,
        members: vec![],
        lines: vec![
            line("src/vocabulary/authority.rs", 4, "use serde::{Deserialize, Serialize};", None),
            line("src/vocabulary/package.rs", 11, "use serde::{Deserialize, Serialize};", None),
        ],
    });
    yours.push(CrateUse {
        name: "store-s3".to_owned(),
        count: 2,
        members: vec![],
        lines: vec![
            line("src/lib.rs", 48, "use serde::{Deserialize, Serialize};", None),
            line("src/pack.rs", 23, "use serde::{Deserialize, Serialize};", None),
        ],
    });
    yours.push(CrateUse {
        name: "control".to_owned(),
        count: 1,
        members: vec![],
        lines: vec![
            line("src/wire.rs", 8, "use serde::{Deserialize, Serialize};", None),
        ],
    });
    yours.push(CrateUse {
        name: "journeys".to_owned(),
        count: 1,
        members: vec![],
        lines: vec![
            line("tests/restart_persistence.rs", 81, "#[derive(Debug, serde::Serialize)]", None),
        ],
    });
    yours.push(CrateUse {
        name: "performance-tests".to_owned(),
        count: 1,
        members: vec![],
        lines: vec![
            line("src/bin/integrated.rs", 45, "use serde::Serialize;", None),
        ],
    });
    yours.push(CrateUse {
        name: "platform".to_owned(),
        count: 1,
        members: vec![],
        lines: vec![
            line("native_path.rs", 3, "use serde::{Deserialize, Serialize};", None),
        ],
    });
    yours.push(CrateUse {
        name: "token-budget".to_owned(),
        count: 1,
        members: vec![],
        lines: vec![
            line("src/main.rs", 17, "use serde::Serialize;", None),
        ],
    });
    Reach { yours, basis: Basis::Scanned, note: Some("A path scan of your crates: real lines, approximate counts.".to_owned()), ..Reach::default() }
}
