//! Pinned from the v6 board's path scan (`Nudox-Design-System/v6/moments/data/sym_uses.json`, `toml@0.8.23` `Value`): real lines from this repository's own crates.
//! Generated by `.local/lanes/wave6/glyph/gen_reach.py`; the counts are the scan's (a path scan, not a compiler).

use crate::anatomy::reach::{Basis, CrateUse, Line, Reach, Reached};
use crate::anatomy::plan::Effect;

const NAME: &str = "Value";

pub(crate) fn toml_value() -> Reach {
    let line = |file: &str, line: u32, text: &str, member: Option<&str>| {
        let mark = text.find(NAME).and_then(|at| u32::try_from(at).ok().zip(u32::try_from(at + NAME.len()).ok()));
        Line { file: file.to_owned(), line, text: text.to_owned(), mark, member: member.map(ToOwned::to_owned), ..Line::default() }
    };
    let mut yours = Vec::new();
    yours.push(CrateUse {
        name: "desktop".to_owned(),
        count: 43,
        members: vec![("as_str".to_owned(), 8), ("as_bool".to_owned(), 3), ("as_table".to_owned(), 2), ("as_array".to_owned(), 2), ("String".to_owned(), 1)],
        lines: vec![
            line("src/harness.rs", 607, "let parsed: toml::Value = toml::from_str(&bytes)", None),
            line("src/harness.rs", 615, ".and_then(toml::Value::as_table)", Some("as_table")),
            line("src/harness.rs", 617, ".and_then(toml::Value::as_array)", Some("as_array")),
            line("src/harness.rs", 636, ".and_then(toml::Value::as_table)", Some("as_table")),
            line("src/harness.rs", 641, "} else if declared.as_table().and_then(|inherit| inherit.get(\"workspace\")).and_then(toml::Value::as_bool) == Some(true) {", Some("as_bool")),
            line("src/harness.rs", 649, ".and_then(|p| p.get(\"edition\")).and_then(toml::Value::as_str).map(str::to_owned);", Some("as_str")),
            line("src/model/local_package/manifest.rs", 33, "dependencies: BTreeMap<String, toml::Value>,", None),
        ],
    });
    yours.push(CrateUse {
        name: "local-service".to_owned(),
        count: 26,
        members: vec![("as_table".to_owned(), 10), ("String".to_owned(), 4), ("as_str".to_owned(), 2), ("Table".to_owned(), 2), ("as_bool".to_owned(), 2)],
        lines: vec![
            line("src/builtin/browse.rs", 183, "let Ok(document) = text.parse::<toml::Value>() else {", None),
            line("src/builtin/browse.rs", 188, ".and_then(toml::Value::as_table)", Some("as_table")),
            line("src/builtin/browse.rs", 191, ".filter_map(toml::Value::as_table)", Some("as_table")),
            line("src/builtin/local_manifest.rs", 21, "fn read_cargo_package_table(project_root: &Path) -> Result<(Vec<u8>, toml::Value), String> {", None),
            line("src/builtin/local_manifest.rs", 24, "let root = toml::from_str::<toml::Value>(", None),
            line("src/builtin/local_manifest.rs", 41, "if let Ok(root) = toml::from_str::<toml::Value>(text) {", None),
            line("src/builtin/local_manifest.rs", 48, ".and_then(toml::Value::as_str)", Some("as_str")),
        ],
    });
    yours.push(CrateUse {
        name: "engine".to_owned(),
        count: 15,
        members: vec![("as_str".to_owned(), 6), ("as_table".to_owned(), 3), ("String".to_owned(), 1), ("Table".to_owned(), 1), ("as_bool".to_owned(), 1), ("as_array".to_owned(), 1)],
        lines: vec![
            line("src/forge/manifest.rs", 93, "fn parse_toml(value: &[u8]) -> Result<toml::Value, ForgeRejectReason> {", None),
            line("src/forge/manifest.rs", 100, "let package = root.get(\"package\").and_then(toml::Value::as_table);", Some("as_table")),
            line("src/forge/manifest.rs", 103, ".and_then(toml::Value::as_str);", Some("as_str")),
            line("src/forge/manifest.rs", 106, ".and_then(toml::Value::as_str);", Some("as_str")),
            line("src/forge/manifest.rs", 135, "let Some(table) = root.get(table_name).and_then(toml::Value::as_table) else {", Some("as_table")),
            line("src/forge/manifest.rs", 140, "toml::Value::String(value) => (value.clone(), false),", Some("String")),
            line("src/forge/manifest.rs", 141, "toml::Value::Table(table) => (", Some("Table")),
        ],
    });
    yours.push(CrateUse {
        name: "advisory".to_owned(),
        count: 13,
        members: vec![("as_str".to_owned(), 8), ("as_table".to_owned(), 2), ("as_array".to_owned(), 1)],
        lines: vec![
            line("src/parse.rs", 141, "let root: toml::Value = front.parse().map_err(|_| RustSecParseError::InvalidToml)?;", None),
            line("src/parse.rs", 144, ".and_then(toml::Value::as_table)", Some("as_table")),
            line("src/parse.rs", 150, ".and_then(toml::Value::as_str)", Some("as_str")),
            line("src/parse.rs", 156, ".and_then(toml::Value::as_str)", Some("as_str")),
            line("src/parse.rs", 162, ".and_then(toml::Value::as_table)", Some("as_table")),
            line("src/parse.rs", 844, ".and_then(toml::Value::as_array)", Some("as_array")),
        ],
    });
    yours.push(CrateUse {
        name: "library".to_owned(),
        count: 5,
        members: vec![("as_array".to_owned(), 2), ("as_str".to_owned(), 2)],
        lines: vec![
            line("browse/cargo.rs", 217, "let document: toml::Value = lockfile", None),
            line("browse/cargo.rs", 222, ".and_then(toml::Value::as_array)", Some("as_array")),
            line("browse/cargo.rs", 230, ".and_then(toml::Value::as_str)", Some("as_str")),
            line("browse/cargo.rs", 242, ".and_then(toml::Value::as_array)", Some("as_array")),
            line("browse/cargo.rs", 245, ".filter_map(toml::Value::as_str)", Some("as_str")),
        ],
    });
    Reach { yours, basis: Basis::Scanned, note: Some("A path scan of your crates: real lines, approximate counts.".to_owned()), ..Reach::default() }
}
