//! Pinned from the v6 board's path scan (`Nudox-Design-System/v6/moments/data/sym_uses.json`, `toml@0.8.23` `Value`): real lines from this repository's own crates.
//! Generated by `.local/lanes/wave6/glyph/gen_reach.py`; the counts are the scan's (a path scan, not a compiler).

use crate::anatomy::plan::Effect;
use crate::anatomy::reach::{Basis, CrateUse, Line, Reach, Reached};

const NAME: &str = "as_str";

pub(crate) fn toml_as_str() -> Reach {
    let line = |file: &str, line: u32, text: &str, member: Option<&str>| {
        let mark = text.find(NAME).and_then(|at| {
            u32::try_from(at)
                .ok()
                .zip(u32::try_from(at + NAME.len()).ok())
        });
        Line {
            file: file.to_owned(),
            line,
            text: text.to_owned(),
            mark,
            member: member.map(ToOwned::to_owned),
            ..Line::default()
        }
    };
    let mut yours = Vec::new();
    yours.push(CrateUse {
        name: "advisory".to_owned(),
        count: 8,
        members: vec![],
        lines: vec![
            line("src/parse.rs", 150, ".and_then(toml::Value::as_str)", None),
            line("src/parse.rs", 156, ".and_then(toml::Value::as_str)", None),
            line("src/parse.rs", 191, ".and_then(toml::Value::as_str)", None),
        ],
    });
    yours.push(CrateUse {
        name: "desktop".to_owned(),
        count: 8,
        members: vec![],
        lines: vec![
            line("src/harness.rs", 649, ".and_then(|p| p.get(\"edition\")).and_then(toml::Value::as_str).map(str::to_owned);", None),
            line("src/model/local_package/manifest.rs", 139, ".and_then(toml::Value::as_str)", None),
            line("src/model/local_package/manifest.rs", 372, "let text = |key: &str| table.get(key).and_then(toml::Value::as_str);", None),
        ],
    });
    yours.push(CrateUse {
        name: "engine".to_owned(),
        count: 6,
        members: vec![],
        lines: vec![
            line(
                "src/forge/manifest.rs",
                103,
                ".and_then(toml::Value::as_str);",
                None,
            ),
            line(
                "src/forge/manifest.rs",
                106,
                ".and_then(toml::Value::as_str);",
                None,
            ),
            line(
                "src/forge/manifest.rs",
                144,
                ".and_then(toml::Value::as_str)",
                None,
            ),
        ],
    });
    yours.push(CrateUse {
        name: "library".to_owned(),
        count: 2,
        members: vec![],
        lines: vec![
            line(
                "browse/cargo.rs",
                230,
                ".and_then(toml::Value::as_str)",
                None,
            ),
            line(
                "browse/cargo.rs",
                245,
                ".filter_map(toml::Value::as_str)",
                None,
            ),
        ],
    });
    yours.push(CrateUse {
        name: "local-service".to_owned(),
        count: 2,
        members: vec![],
        lines: vec![
            line(
                "src/builtin/local_manifest.rs",
                48,
                ".and_then(toml::Value::as_str)",
                None,
            ),
            line(
                "src/builtin/local_manifest.rs",
                282,
                ".and_then(toml::Value::as_str)",
                None,
            ),
        ],
    });
    Reach {
        yours,
        basis: Basis::Scanned,
        note: Some("A path scan of your crates: real lines, approximate counts.".to_owned()),
        ..Reach::default()
    }
}
