[package]
name = "backend-semantic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
blake3 = { workspace = true }
backend-version = { path = "../version" }
backend-flow = { path = "../flow" }
memmap2 = { version = "0.9.9", optional = true }
serde.workspace = true
thiserror.workspace = true

[features]
mmap = ["dep:memmap2"]

[dev-dependencies]
allocation-counter.workspace = true
serde_json.workspace = true

[lints]
workspace = true
