cargo-features = ["codegen-backend"]

[workspace]
resolver = "3"
members = [
  "./compiler",
  "./ir",
  "./terminusdb",
]
default-members = ["./compiler"]

[workspace.package]
edition = "2024"
publish = false

[workspace.dependencies]
ir = { path = "./ir" }
terminusdb = { path = "./terminusdb" }

[profile.dev]
codegen-backend = "cranelift"
