color = "Never"
edition = "2024"
format_macro_matchers = true
format_macro_bodies = true
hex_literal_case = "Lower"
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = false
overflow_delimited_expr = true
use_field_init_shorthand = true
style_edition = "2024"
wrap_comments = true
