[package]
name = "backend-frontend-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
[lints]
workspace = true
[dependencies]
backend-compile = { path = "../../crates/compile" }
backend-semantic = { path = "../../crates/semantic" }
blake3.workspace = true
ruff_python_ast = "=0.0.8"
ruff_python_parser = "=0.0.8"
ruff_text_size = "=0.0.8"
tree-sitter-python = "=0.25.0"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
[lib]
path = "lib.rs"
