load("//build:rust.bzl", "deps", "rust_crate")

rust_crate(
    name = "ir",
    features = ["facet", "serde"],
    deps = deps(crates = [
        "facet",
        "serde",
        "yoke",
        "arborium_tree_sitter",
        "rustc_hash",
        "thiserror",
    ]),
)
