//! Nix derivation backend — daemon sandbox + content-addressed output cache.
//!
//! For compile-heavy producers (design §5.3): generate a small derivation whose
//! builder runs the [`Spec`] command with network off. The Nix daemon provides
//! namespaces, seccomp, and store caching; we do not reimplement the cage.
//!
//! Selection: `NUDOX_SANDBOX=nix` when `nix` is on PATH. Per-producer policy
//! can still prefer LinuxBwrap for tiny packages (design §16.2).

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::Instant;

use crate::backend::{Backend, Capabilities};
use crate::error::{KillReason, SandboxError};
use crate::limits::Network;
use crate::spec::{Output, Spec};

/// Run a [`Spec`] inside a Nix build sandbox.
#[derive(Debug, Clone)]
pub struct NixDerivation {
	nix: PathBuf,
}

impl NixDerivation {
	/// Locate `nix` / `nix-build`.
	pub fn new() -> Self {
		let nix = which::which("nix")
			.or_else(|_| which::which("nix-build"))
			.unwrap_or_else(|_| PathBuf::from("nix"));
		Self { nix }
	}

	/// Whether a Nix CLI appears usable.
	pub fn probe_available(&self) -> bool {
		Command::new(&self.nix)
			.arg("--version")
			.stdout(Stdio::null())
			.stderr(Stdio::null())
			.status()
			.map(|s| s.success())
			.unwrap_or(false)
	}

	fn write_expression(&self, spec: &Spec, work: &Path) -> Result<PathBuf, SandboxError> {
		let builder = work.join("builder.sh");
		let expr = work.join("default.nix");

		let sh_escape = |s: &str| s.replace('\'', "'\\''");
		let cmd = which::which(&spec.command).unwrap_or_else(|_| spec.command.clone());

		let mut script = String::from("set -eu\nexport HOME=\"$TMPDIR\"\n");
		for (k, v) in spec.env.iter() {
			script.push_str(&format!(
				"export '{}'='{}'\n",
				sh_escape(&k.to_string_lossy()),
				sh_escape(&v.to_string_lossy())
			));
		}
		if let Some(cwd) = &spec.cwd {
			script.push_str(&format!(
				"cd '{}'\n",
				sh_escape(&cwd.display().to_string())
			));
		}
		script.push_str(&format!("'{}'", sh_escape(&cmd.display().to_string())));
		for a in &spec.args {
			script.push_str(&format!(" '{}'", sh_escape(&a.to_string_lossy())));
		}
		script.push_str(" > \"$out\"\n");
		fs::write(&builder, script)?;

		// Touch path strings so store paths appear as derivation inputs when
		// they already live under /nix/store.
		let mut path_adds = String::new();
		for p in spec
			.mounts
			.read_only
			.iter()
			.chain(spec.mounts.writable.iter())
		{
			if p.exists() {
				path_adds.push_str(&format!("    {}\n", nix_str(&p.display().to_string())));
			}
		}

		let nix_text = format!(
			r#"# Generated by nudox sandbox NixDerivation — do not edit.
let
  builder = {builder_path};
  extraPaths = [
{path_adds}  ];
in
derivation {{
  name = "nudox-sandbox-job";
  system = builtins.currentSystem;
  builder = "/bin/sh";
  args = [ "-e" builder ];
  preferLocalBuild = true;
  allowSubstitutes = true;
  inherit extraPaths;
}}
"#,
			builder_path = format!(
				"(builtins.path {{ path = {}; name = \"builder.sh\"; }})",
				nix_str(&builder.display().to_string())
			),
			path_adds = path_adds,
		);
		fs::write(&expr, nix_text)?;
		Ok(expr)
	}
}

impl Default for NixDerivation {
	fn default() -> Self {
		Self::new()
	}
}

fn nix_str(s: &str) -> String {
	format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

impl Backend for NixDerivation {
	fn name(&self) -> &'static str {
		"nix-derivation"
	}

	fn capabilities(&self) -> Capabilities {
		Capabilities {
			isolation: true,
			network_off: true,
			fs_scope: true,
			seccomp: true,
			cgroups: true,
			production_grade: true,
		}
	}

	fn run(&self, spec: Spec) -> Result<Output, SandboxError> {
		if matches!(spec.network, Network::On) {
			return Err(SandboxError::Denied {
				reason: "NixDerivation refuses Network::On (use FOD fetch or LinuxBwrap)".into(),
			});
		}

		let work = std::env::temp_dir().join(format!(
			"nudox-nixdrv-{}-{}",
			std::process::id(),
			std::time::SystemTime::now()
				.duration_since(std::time::UNIX_EPOCH)
				.map(|d| d.as_nanos())
				.unwrap_or(0)
		));
		fs::create_dir_all(&work)?;
		let expr = self.write_expression(&spec, &work)?;

		let start = Instant::now();
		let deadline = spec.limits.wall;

		let mut cmd = Command::new(&self.nix);
		if self.nix.file_name().and_then(|s| s.to_str()) == Some("nix") {
			// --impure: builder script is an absolute host path (content-addressed
			// via builtins.path). Guest still runs network-off in the daemon sandbox.
			cmd.args(["build", "-f"]);
			cmd.arg(&expr);
			cmd.args(["--no-link", "--print-out-paths", "--impure"]);
		} else {
			cmd.arg(&expr).arg("--no-out-link");
		}
		cmd.stdin(Stdio::null())
			.stdout(Stdio::piped())
			.stderr(Stdio::piped())
			.env_clear()
			.env(
				"PATH",
				std::env::var_os("PATH").unwrap_or_else(|| "/usr/bin:/bin".into()),
			)
			.env(
				"NIX_PATH",
				std::env::var_os("NIX_PATH").unwrap_or_default(),
			)
			.env(
				"HOME",
				std::env::var_os("HOME").unwrap_or_else(|| "/tmp".into()),
			);

		for key in ["NIX_CONFIG", "XDG_CACHE_HOME", "XDG_CONFIG_HOME"] {
			if let Ok(v) = std::env::var(key) {
				cmd.env(key, v);
			}
		}

		let output = cmd.output().map_err(SandboxError::Spawn)?;
		let wall = start.elapsed();
		if wall > deadline {
			return Err(SandboxError::Killed {
				reason: KillReason::Wall,
				wall,
			});
		}
		if !output.status.success() {
			let stderr = String::from_utf8_lossy(&output.stderr);
			let _ = fs::remove_dir_all(&work);
			return Err(SandboxError::Backend(format!("nix-build failed: {stderr}")));
		}

		let out_path = String::from_utf8_lossy(&output.stdout)
			.lines()
			.next()
			.unwrap_or("")
			.trim()
			.to_string();
		if out_path.is_empty() {
			let _ = fs::remove_dir_all(&work);
			return Err(SandboxError::Backend(
				"nix-build produced no out path".into(),
			));
		}
		let stdout = fs::read(&out_path).unwrap_or_default();
		if stdout.len() > spec.limits.max_stdout {
			let _ = fs::remove_dir_all(&work);
			return Err(SandboxError::Killed {
				reason: KillReason::OutputCap,
				wall,
			});
		}

		let status = Command::new("true")
			.status()
			.map_err(SandboxError::Spawn)?;
		let _ = fs::remove_dir_all(&work);

		Ok(Output {
			stdout,
			stderr: output.stderr,
			status,
			wall,
			peak_mem: None,
			killed: None,
		})
	}
}

/// Prefer NixDerivation when env requests it and nix is present.
pub fn prefer_nix_derivation() -> bool {
	matches!(
		std::env::var("NUDOX_SANDBOX").as_deref(),
		Ok("nix") | Ok("nix-derivation") | Ok("derivation")
	)
}
