[package]
name = "nudox-compile-publication"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nudox-id = { path = "../nudox-id" }
nudox-ir-format = { path = "../nudox-ir-format" }
thiserror.workspace = true

[dev-dependencies]
nudox-compile-vocab = { path = "../nudox-compile-vocab" }
nudox-ir-vocab = { path = "../nudox-ir-vocab" }

[lib]
path = "src/lib.rs"
