[package]
name = "nudox-compile-publication"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nudox-compile-vocab = { path = "../nudox-compile-vocab" }
nudox-compile-driver = { path = "../nudox-compile-driver" }
nudox-durable-journal = { path = "../nudox-durable-journal" }
nudox-hydration = { path = "../nudox-hydration" }
nudox-id = { path = "../nudox-id" }
nudox-ir-format = { path = "../nudox-ir-format" }
nudox-object = { path = "../nudox-object" }
nudox-root = { path = "../nudox-root" }
nudox-schema = { path = "../nudox-schema" }
nudox-store-memory = { path = "../nudox-store-memory" }
thiserror.workspace = true

[dev-dependencies]
nudox-ir-vocab = { path = "../nudox-ir-vocab" }

[lib]
path = "src/lib.rs"
