//! The four bundled faces, their static cuts, and the typesetting helper.
//!
//! GPUI registers a variable font as a single face (its default instance) and
//! never applies `wght`, `wdth` or `opsz`, so every weight the type ladder
//! uses is shipped as a static cut (`resources/fonts/static`, generated by
//! `resources/fonts/instance.py`). Families:
//!
//! | family | cuts | used for |
//! |---|---|---|
//! | `Bricolage Grotesque` | 520 / 620 / 650 / 720, opsz 18 | text-size display heads |
//! | `Bricolage Grotesque Display` | 620 / 640, opsz 96 | [`ty::DISPLAY`], [`ty::DISPLAY_XL`] |
//! | `Bricolage Grotesque Hero` | 640, opsz 96, wdth 92 | [`ty::HERO`] |
//! | `Bricolage Grotesque Book` | 640, opsz 17, wdth 95 | [`ty::BOOK`] |
//! | `Geist` | 400 / 500 / 600 / 700 | UI |
//! | `Geist Mono` | 400 (variable default), 500, 600 | identifiers |
//! | `Newsreader` | italic 400 opsz 14; upright variable default | serif below 17 px |
//! | `Newsreader Lede` | italic 400 opsz 19 | [`ty::LEDE`] and larger serif |
//!
//! Views never name a family: they call [`Typeset::typeset`] with a
//! [`TypeRole`] and the active [`Facet`].

use crate::theme::Facet;
use crate::tokens::{Face, TypeRole, ty};
use gpui::{App, FontFeatures, FontStyle, FontWeight, SharedString, Styled, px};
use sha2::{Digest, Sha256};
use std::borrow::Cow;
use std::fmt;
use std::sync::{Arc, LazyLock};

#[cfg(feature = "gallery")]
pub(crate) mod gallery;

/// One embedded font file.
#[derive(Clone, Copy, Debug)]
pub struct Cut {
    /// The file name under `resources/fonts`.
    pub file: &'static str,
    /// The family name `CoreText` resolves for this cut.
    pub family: &'static str,
    /// The face this cut belongs to.
    pub face: Face,
    /// The weight baked into the cut (its `OS/2` weight class).
    pub weight: f32,
    /// Whether the cut is italic.
    pub italic: bool,
    /// SHA-256 of the embedded bytes.
    pub sha256: &'static str,
    /// The font bytes.
    pub bytes: &'static [u8],
}

/// The general text-size display family (opsz 18).
pub const DISPLAY_TEXT: &str = "Bricolage Grotesque";
/// The display-size cuts (opsz 96) for section heads and board heroes.
pub const DISPLAY_LARGE: &str = "Bricolage Grotesque Display";
/// The page hero cut (opsz 96, wdth 92).
pub const DISPLAY_HERO: &str = "Bricolage Grotesque Hero";
/// The shelf book title cut (opsz 17, wdth 95).
pub const DISPLAY_BOOK: &str = "Bricolage Grotesque Book";
/// The UI family.
pub const UI: &str = "Geist";
/// The identifier family.
pub const MONO: &str = "Geist Mono";
/// The serif family (always set italic); its italic cut is opsz 14.
pub const SERIF: &str = "Newsreader";
/// The lede-size serif (italic, opsz 19).
pub const SERIF_LEDE: &str = "Newsreader Lede";

macro_rules! cut {
    ($file:literal, $family:expr, $face:ident, $weight:literal, $italic:literal, $sha:literal) => {
        Cut {
            file: $file,
            family: $family,
            face: Face::$face,
            weight: $weight,
            italic: $italic,
            sha256: $sha,
            bytes: include_bytes!(concat!("../resources/fonts/", $file)),
        }
    };
}

/// Every embedded cut, in registration order.
pub static CUTS: [Cut; 18] = [
    cut!(
        "static/BricolageGrotesque-520.ttf",
        DISPLAY_TEXT,
        Display,
        520.0,
        false,
        "41b0852b0605cff589436752c61c63600cb5804ca06bde51234e106354ff82b4"
    ),
    cut!(
        "static/BricolageGrotesque-620.ttf",
        DISPLAY_TEXT,
        Display,
        620.0,
        false,
        "f25c469d978eaa65b16bfae58fdfc793ca2d74111487f0be46dc21ff7f33619f"
    ),
    cut!(
        "static/BricolageGrotesque-650.ttf",
        DISPLAY_TEXT,
        Display,
        650.0,
        false,
        "4577e68bff6b76c37c6e38a1f50dcc69acb7eedeb2e7293b24397faa40b9d815"
    ),
    cut!(
        "static/BricolageGrotesque-720.ttf",
        DISPLAY_TEXT,
        Display,
        720.0,
        false,
        "3653ceea8a8a79d8b764f28fb9677496b1173ee6dcd1d994d5b57efbbc4f257d"
    ),
    cut!(
        "static/BricolageGrotesqueDisplay-620.ttf",
        DISPLAY_LARGE,
        Display,
        620.0,
        false,
        "79fa276a88321defc1d3e6cc5b9d8868c133a8f2cf0dc26eb21ea3d43b48e742"
    ),
    cut!(
        "static/BricolageGrotesqueDisplay-640.ttf",
        DISPLAY_LARGE,
        Display,
        640.0,
        false,
        "5adf281c265b8fe1a8f345c83e8ad896f9c12f18aaa9fb9237df56c16d71ad6b"
    ),
    cut!(
        "static/BricolageGrotesqueHero-640.ttf",
        DISPLAY_HERO,
        Display,
        640.0,
        false,
        "9976d02f919254ade2794b256fee542c0000774ec084d7c95b717e8eaa188a24"
    ),
    cut!(
        "static/BricolageGrotesqueBook-640.ttf",
        DISPLAY_BOOK,
        Display,
        640.0,
        false,
        "dd38dca08eb587b57c855f4488484e2199b24cbd780327756595686d4ac5f28a"
    ),
    cut!(
        "static/Geist-400.ttf",
        UI,
        Ui,
        400.0,
        false,
        "05df92b7b61c1c3a21af8923c1babe141f8751ddc693fa8d1c784608aa741c3b"
    ),
    cut!(
        "static/Geist-500.ttf",
        UI,
        Ui,
        500.0,
        false,
        "9c07b78b7c01b18647bc320603eafcddbace7d99bb2bf448dae92cb2a86844f1"
    ),
    cut!(
        "static/Geist-600.ttf",
        UI,
        Ui,
        600.0,
        false,
        "31976fec5c66e823d1af6f04664bd9f2bb6c8116fdb7da5aa54fdd2d68cb6467"
    ),
    cut!(
        "static/Geist-700.ttf",
        UI,
        Ui,
        700.0,
        false,
        "7bc132412cd1d42eab46796a252a3b66975d400194daa7a16b1e78bf313c0cf0"
    ),
    cut!(
        "GeistMono[wght].ttf",
        MONO,
        Mono,
        400.0,
        false,
        "87c2aff9723544a9adaea19d92e42a33705c9723624801b6e0224c2206a6af0d"
    ),
    cut!(
        "static/GeistMono-500.ttf",
        MONO,
        Mono,
        500.0,
        false,
        "befe90a2ec1c86541447d1492a04ad6fb25252248524e7eb27c80ff87723a59a"
    ),
    cut!(
        "static/GeistMono-600.ttf",
        MONO,
        Mono,
        600.0,
        false,
        "a14b0e1f4785fa208884b508098f3d93ca850a24f0894cfe5ded2b5357ea4798"
    ),
    cut!(
        "static/Newsreader-Italic-400.ttf",
        SERIF,
        Serif,
        400.0,
        true,
        "59bfae7f8d113757d2a1bd2496582e4cc582bd87b24a1f44b4ca4f0f92a7e0fa"
    ),
    cut!(
        "static/NewsreaderLede-Italic-400.ttf",
        SERIF_LEDE,
        Serif,
        400.0,
        true,
        "8dbb7a00aa0d33309428f2ede9174e61054baca2a8e92d0dfde66a954f1a6809"
    ),
    cut!(
        "Newsreader[opsz,wght].ttf",
        SERIF,
        Serif,
        400.0,
        false,
        "8a08d13f8a6c0d51be379a60af84f945f65369a67e509ee3c3bdcc421254d7c1"
    ),
];

/// A bundled font whose bytes no longer match the manifest.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FontMismatch {
    /// The offending file.
    pub file: &'static str,
    /// Its actual SHA-256.
    pub actual: String,
}

impl fmt::Display for FontMismatch {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "bundled font {} has SHA-256 {}; the manifest pins another",
            self.file, self.actual
        )
    }
}

impl std::error::Error for FontMismatch {}

/// Checks every embedded cut against its pinned hash.
///
/// # Errors
/// The first cut whose bytes changed.
pub fn verify() -> Result<(), FontMismatch> {
    for cut in &CUTS {
        let actual = format!("{:x}", Sha256::digest(cut.bytes));
        if actual != cut.sha256 {
            return Err(FontMismatch {
                file: cut.file,
                actual,
            });
        }
    }
    Ok(())
}

/// Verifies and registers every cut with GPUI's text system. Call once per
/// app, before the first window.
///
/// # Errors
/// A hash mismatch, or the platform refusing a font.
pub fn install(cx: &App) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    verify()?;
    let fonts = CUTS
        .iter()
        .map(|cut| Cow::Borrowed(cut.bytes))
        .collect::<Vec<_>>();
    cx.text_system()
        .add_fonts(fonts)
        .map_err(|error| error.to_string().into())
}

/// The family a role resolves to. GPUI then picks the cut nearest the role's
/// weight inside that family (CSS font matching).
#[must_use]
pub fn family(role: TypeRole) -> &'static str {
    match role.face {
        Face::Display if role == ty::HERO => DISPLAY_HERO,
        Face::Display if role == ty::BOOK => DISPLAY_BOOK,
        // The boards pin `opsz 96` on every display-size head.
        Face::Display if role.size >= 24.0 => DISPLAY_LARGE,
        Face::Display => DISPLAY_TEXT,
        Face::Ui => UI,
        Face::Mono => MONO,
        // Chrome sets opsz to the px size; two cuts bracket the ladder.
        Face::Serif if role.size >= 17.0 && role.italic => SERIF_LEDE,
        Face::Serif => SERIF,
    }
}

/// The cut GPUI will select for a role (CSS weight matching within
/// [`family`]); used by tests and the type sheet's annotations.
#[must_use]
pub fn cut(role: TypeRole) -> &'static Cut {
    let family = family(role);
    let candidates = || {
        CUTS.iter()
            .filter(move |cut| cut.family == family && cut.italic == role.italic)
    };
    let wanted = role.weight;
    // CSS Fonts 4 §5.2: for weights above 500 look up first, then down; for
    // 400..=500 look up to 500, then down, then up; below 400 look down first.
    let up = |limit: f32| {
        candidates()
            .filter(move |cut| cut.weight >= wanted && cut.weight <= limit)
            .min_by(|a, b| a.weight.total_cmp(&b.weight))
    };
    let down = || {
        candidates()
            .filter(|cut| cut.weight < wanted)
            .max_by(|a, b| a.weight.total_cmp(&b.weight))
    };
    let chosen = if wanted > 500.0 {
        up(f32::MAX).or_else(down)
    } else if wanted >= 400.0 {
        up(500.0).or_else(down).or_else(|| up(f32::MAX))
    } else {
        down().or_else(|| up(f32::MAX))
    };
    chosen.unwrap_or(&CUTS[8])
}

/// The font features a role turns on.
///
/// Every mono role asks for `zero` (the boards' `.mono` / `.code` rule) and
/// turns `liga` off: the boards render `->` and `=>` as typed, never as
/// Geist Mono's arrow ligatures, and an identifier must read exactly as it is
/// spelled. Geist Mono 1.7 ships no `zero` feature (its default zero is
/// already slashed, as on the boards), so that request is a documented no-op
/// kept for spec parity. `.code`'s `ss02` is not applied: the rendered boards
/// show the default double-storey `a`.
#[must_use]
pub fn features(role: TypeRole) -> FontFeatures {
    static MONO: LazyLock<FontFeatures> = LazyLock::new(|| {
        FontFeatures(Arc::new(vec![
            ("zero".to_owned(), 1),
            ("liga".to_owned(), 0),
        ]))
    });
    match role.face {
        Face::Mono => MONO.clone(),
        Face::Display | Face::Ui | Face::Serif => FontFeatures::default(),
    }
}

/// Sets a [`TypeRole`] on any styled element: family, weight, size, line
/// height, tracking, italic and features, all at the facet's text scale.
pub trait Typeset: Styled + Sized {
    /// Typesets with the active facet's text scale.
    #[must_use]
    fn typeset(self, role: TypeRole, facet: &Facet) -> Self {
        self.typeset_at(role, facet.text_scale)
    }

    /// Typesets at an explicit text scale (1.0 = 100 %).
    #[must_use]
    fn typeset_at(mut self, role: TypeRole, scale: f32) -> Self {
        let size = role.size * scale;
        let text = self.text_style();
        text.font_family = Some(SharedString::new_static(family(role)));
        text.font_weight = Some(FontWeight(role.weight));
        text.font_style = Some(if role.italic {
            FontStyle::Italic
        } else {
            FontStyle::Normal
        });
        text.font_features = Some(features(role));
        text.font_size = Some(px(size).into());
        text.line_height = Some(px(role.line * scale).into());
        text.letter_spacing = Some(px(role.tracking * size));
        self
    }
}

impl<E: Styled> Typeset for E {}

#[cfg(test)]
mod tests {
    use super::{CUTS, cut, family, verify};
    use crate::tokens::{Face, TypeRole, ty};

    const ROLES: [TypeRole; 22] = [
        ty::DISPLAY_XL,
        ty::HERO,
        ty::DISPLAY,
        ty::TITLE,
        ty::BOOK,
        ty::DEPTH,
        ty::HEAD,
        ty::DIALOG,
        ty::PROSE,
        ty::BODY,
        ty::ROW,
        ty::BUTTON,
        ty::SMALL,
        ty::LABEL,
        ty::STATUS,
        ty::CODE,
        ty::MONO_ROW,
        ty::MONO_SMALL,
        ty::LEDE,
        ty::MARGIN,
        ty::CAPTION,
        ty::AXIS,
    ];

    #[test]
    fn manifest_matches_embedded_bytes() {
        assert_eq!(verify(), Ok(()));
    }

    #[test]
    fn every_role_has_an_exact_cut() {
        for role in ROLES {
            let chosen = cut(role);
            assert_eq!(chosen.family, family(role));
            assert_eq!(chosen.italic, role.italic, "{role:?}");
            // The ladder never asks for a weight it has to approximate,
            // except TITLE (650), which has its own cut.
            assert!(
                (chosen.weight - role.weight).abs() < 0.5,
                "{role:?} resolves to {} {}",
                chosen.family,
                chosen.weight
            );
        }
    }

    #[test]
    fn display_roles_pick_their_optical_family() {
        assert_eq!(family(ty::HERO), super::DISPLAY_HERO);
        assert_eq!(family(ty::BOOK), super::DISPLAY_BOOK);
        assert_eq!(family(ty::DISPLAY_XL), super::DISPLAY_LARGE);
        assert_eq!(family(ty::DISPLAY), super::DISPLAY_LARGE);
        assert_eq!(family(ty::TITLE), super::DISPLAY_TEXT);
        assert_eq!(family(ty::DEPTH), super::DISPLAY_TEXT);
        assert_eq!(family(ty::LEDE), super::SERIF_LEDE);
        assert_eq!(family(ty::CAPTION), super::SERIF);
        assert!(
            CUTS.iter()
                .all(|cut| cut.face != Face::Serif || cut.family.starts_with(super::SERIF))
        );
    }
}
