[package]
name = "wave-application-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
arrayvec.workspace = true
nudox-adaptive = { path = "../nudox-adaptive" }
nudox-compile-registry = { path = "../nudox-compile-registry" }
nudox-compile-vocab = { path = "../nudox-compile-vocab" }
nudox-id = { path = "../nudox-id" }
nudox-observe = { path = "../nudox-observe" }

[dev-dependencies]
allocation-counter.workspace = true

[lints.rust]
unsafe_code = "deny"
unused_lifetimes = "warn"
unused_qualifications = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
dbg_macro = "deny"
exit = "deny"
mem_forget = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
