[package]
name = "backend-performance-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
backend-engine = { path = "../../crates/engine" }
backend-execution = { path = "../../crates/execution" }
backend-flow = { path = "../../crates/flow" }
backend-replication = { path = "../../crates/replication" }
backend-semantic = { path = "../../crates/semantic" }
backend-store = { path = "../../crates/store" }
backend-version = { path = "../../crates/version" }

[lints]
workspace = true
