[package]
name = "backend-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
backend-engine = { path = "../engine" }
backend-library = { path = "../library" }
backend-semantic = { path = "../semantic" }
backend-replication = { path = "../replication" }
blake3.workspace = true
hashlink = "=0.12.2"
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "net", "time"] }

[lints]
workspace = true
