[package]
name = "nudox-index-graph-vector"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nudox-id = { path = "../nudox-id" }
nudox-index-vocab = { path = "../nudox-index-vocab" }
nudox-ir-vocab = { path = "../nudox-ir-vocab" }
loom = { workspace = true, optional = true }

[dev-dependencies]
allocation-counter.workspace = true

[features]
loom-model = ["dep:loom"]
