[package]
name = "ir-stream"
edition.workspace = true
version.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
path = "lib.rs"

[dependencies]
heart       = { path = "../heart" }
nudox-ir    = { path = "../nudox-ir" }
nudox-change = { path = "../nudox-change" }
postcard = { version = "1.0", features = ["use-std"] }
serde    = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
