[package]
name = "nudox-e2e"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nudox-frame = { path = "../nudox-frame" }
nudox-hydration = { path = "../nudox-hydration" }
nudox-id = { path = "../nudox-id" }
nudox-object = { path = "../nudox-object" }
nudox-observe = { path = "../nudox-observe" }
nudox-operation = { path = "../nudox-operation" }
nudox-root = { path = "../nudox-root" }
nudox-runtime = { path = "../nudox-runtime" }
nudox-schema = { path = "../nudox-schema" }
nudox-store-memory = { path = "../nudox-store-memory" }
nudox-view = { path = "../nudox-view" }
nudox-workflow = { path = "../nudox-workflow" }
thiserror.workspace = true

[dev-dependencies]
rstest.workspace = true

[lints]
workspace = true
