//! Discovers harness directories and emits the dispatch table.
//!
//! Adding `targets/<id>/` is the only Rust edit required for a new harness.
//! This script refuses a directory that is missing its oracle, cap, or seeds.

use std::fmt::Write;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo::rustc-check-cfg=cfg(fuzzing_libfuzzer)");
    let manifest = env_path("CARGO_MANIFEST_DIR");
    let out_dir = env_path("OUT_DIR");
    let targets_dir = manifest.join("targets");
    println!("cargo::rerun-if-changed={}", display(&targets_dir));

    let mut names = Vec::new();
    let entries = read_dir(&targets_dir);
    for entry in entries {
        let entry = match entry {
            Ok(entry) => entry,
            Err(error) => fail(&format!("reading {}: {error}", display(&targets_dir))),
        };
        let file_type = match entry.file_type() {
            Ok(file_type) => file_type,
            Err(error) => fail(&format!("target type: {error}")),
        };
        if file_type.is_symlink() {
            fail(&format!(
                "{} is a symlink; harness directories must be real directories",
                display(&entry.path())
            ));
        }
        if !file_type.is_dir() {
            continue;
        }
        let Some(name) = entry.file_name().into_string().ok() else {
            fail("a harness directory name is not utf-8");
        };
        if name.starts_with('.') {
            continue;
        }
        if !is_target_id(&name) {
            fail(&format!(
                "harness id {name} must match [a-z][a-z0-9-]* so the flake attr is bare"
            ));
        }
        require_file(&entry.path().join("oracle.rs"));
        require_file(&entry.path().join("max_len"));
        require_file(&entry.path().join("dictionary.txt"));
        require_file(&entry.path().join("score.nix"));
        let corpus = entry.path().join("corpus");
        require_file(&corpus.join("canonical"));
        require_file(&corpus.join("empty"));
        require_file(&corpus.join("bad_magic"));
        println!("cargo::rerun-if-changed={}", display(&entry.path()));
        names.push(name);
    }
    if names.is_empty() {
        fail("tests/fuzz/targets has no harness directories");
    }
    names.sort();

    let mut source = String::from("// Generated by tests/fuzz/build.rs. Do not edit.\n");
    for name in &names {
        let ident = name.replace('-', "_");
        let oracle = display(&targets_dir.join(name).join("oracle.rs"));
        if oracle.contains('"') || oracle.contains('\\') {
            fail(&format!(
                "oracle path {oracle} cannot be emitted as a Rust string"
            ));
        }
        emit(
            &mut source,
            format_args!("#[path = \"{oracle}\"]\nmod {ident};\n"),
        );
        emit(
            &mut source,
            format_args!(
                "const _: () = assert!({ident}::MAX_LEN > 0 && {ident}::MAX_LEN <= 1024 * 1024);\n"
            ),
        );
    }
    emit(
        &mut source,
        format_args!("pub(super) static TARGETS: &[crate::Target] = &[\n"),
    );
    for name in &names {
        let ident = name.replace('-', "_");
        emit(
            &mut source,
            format_args!(
                "crate::Target {{ name: \"{name}\", max_len: {ident}::MAX_LEN, exercise: {ident}::exercise, judge: {ident}::judge, canonical: {ident}::canonical }},\n"
            ),
        );
    }
    emit(&mut source, format_args!("];\n"));

    let destination = out_dir.join("dispatch.rs");
    if let Err(error) = fs::write(&destination, source) {
        fail(&format!("writing {}: {error}", display(&destination)));
    }
}

fn emit(source: &mut String, args: std::fmt::Arguments<'_>) {
    if source.write_fmt(args).is_err() {
        fail("formatting the harness dispatch table");
    }
}

fn env_path(key: &str) -> PathBuf {
    match std::env::var(key) {
        Ok(value) => PathBuf::from(value),
        Err(error) => fail(&format!("{key} is unset: {error}")),
    }
}

fn read_dir(path: &Path) -> fs::ReadDir {
    match fs::read_dir(path) {
        Ok(entries) => entries,
        Err(error) => fail(&format!("reading {}: {error}", display(path))),
    }
}

fn require_file(path: &Path) {
    match fs::metadata(path) {
        Ok(metadata) if metadata.is_file() => {}
        Ok(_) => fail(&format!("{} must be a regular file", display(path))),
        Err(error) => fail(&format!("missing {}: {error}", display(path))),
    }
}

fn is_target_id(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    first.is_ascii_lowercase()
        && chars.all(|character| {
            character.is_ascii_lowercase() || character.is_ascii_digit() || character == '-'
        })
}

fn display(path: &Path) -> String {
    path.display().to_string()
}

fn fail(message: &str) -> ! {
    eprintln!("{message}");
    std::process::exit(1);
}
