[package]
name = "nudox-fuzz"
version = "0.1.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
nudox-ir = { path = "../../workspace/ir/model" }

[[bin]]
name = "decode-entry"
path = "fuzz_targets/decode_entry.rs"
test = false
doc = false
bench = false

[[bin]]
name = "decode-body"
path = "fuzz_targets/decode_body.rs"
test = false
doc = false
bench = false
