// @generated by apps/facet/assets/icons/gen_icons.py — do not edit.

// Lookup tables: several rows legitimately share a value.
#![allow(clippy::match_same_arms)]

use crate::tokens::{Family, Voice};

/// The 50 UI icons (`.ico`).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, PartialOrd, Ord)]
pub enum Icon {
    /// `search`
    Search,
    /// `orbit`
    Orbit,
    /// `package`
    Package,
    /// `layers`
    Layers,
    /// `trail`
    Trail,
    /// `rose`
    Rose,
    /// `mosaic`
    Mosaic,
    /// `comb`
    Comb,
    /// `peel`
    Peel,
    /// `book`
    Book,
    /// `file`
    File,
    /// `folder`
    Folder,
    /// `seal`
    Seal,
    /// `shield-check`
    ShieldCheck,
    /// `lock`
    Lock,
    /// `key`
    Key,
    /// `eye`
    Eye,
    /// `pin`
    Pin,
    /// `bookmark`
    Bookmark,
    /// `tag`
    Tag,
    /// `bell`
    Bell,
    /// `inbox`
    Inbox,
    /// `msg`
    Msg,
    /// `note`
    Note,
    /// `user`
    User,
    /// `users`
    Users,
    /// `settings`
    Settings,
    /// `filter`
    Filter,
    /// `clock`
    Clock,
    /// `history`
    History,
    /// `globe`
    Globe,
    /// `target`
    Target,
    /// `spark`
    Spark,
    /// `zap`
    Zap,
    /// `play`
    Play,
    /// `copy`
    Copy,
    /// `link`
    Link,
    /// `side-l`
    SideL,
    /// `peek`
    Peek,
    /// `split`
    Split,
    /// `grid`
    Grid,
    /// `list`
    List,
    /// `more`
    More,
    /// `alert`
    Alert,
    /// `info`
    Info,
    /// `diamond`
    Diamond,
    /// `crown`
    Crown,
    /// `heart`
    Heart,
    /// `cursor`
    Cursor,
    /// `server`
    Server,
}

impl Icon {
    /// Every icon, in board order.
    pub const ALL: [Self; 50] = [
        Self::Search,
        Self::Orbit,
        Self::Package,
        Self::Layers,
        Self::Trail,
        Self::Rose,
        Self::Mosaic,
        Self::Comb,
        Self::Peel,
        Self::Book,
        Self::File,
        Self::Folder,
        Self::Seal,
        Self::ShieldCheck,
        Self::Lock,
        Self::Key,
        Self::Eye,
        Self::Pin,
        Self::Bookmark,
        Self::Tag,
        Self::Bell,
        Self::Inbox,
        Self::Msg,
        Self::Note,
        Self::User,
        Self::Users,
        Self::Settings,
        Self::Filter,
        Self::Clock,
        Self::History,
        Self::Globe,
        Self::Target,
        Self::Spark,
        Self::Zap,
        Self::Play,
        Self::Copy,
        Self::Link,
        Self::SideL,
        Self::Peek,
        Self::Split,
        Self::Grid,
        Self::List,
        Self::More,
        Self::Alert,
        Self::Info,
        Self::Diamond,
        Self::Crown,
        Self::Heart,
        Self::Cursor,
        Self::Server,
    ];

    /// The board name.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Search => "search",
            Self::Orbit => "orbit",
            Self::Package => "package",
            Self::Layers => "layers",
            Self::Trail => "trail",
            Self::Rose => "rose",
            Self::Mosaic => "mosaic",
            Self::Comb => "comb",
            Self::Peel => "peel",
            Self::Book => "book",
            Self::File => "file",
            Self::Folder => "folder",
            Self::Seal => "seal",
            Self::ShieldCheck => "shield-check",
            Self::Lock => "lock",
            Self::Key => "key",
            Self::Eye => "eye",
            Self::Pin => "pin",
            Self::Bookmark => "bookmark",
            Self::Tag => "tag",
            Self::Bell => "bell",
            Self::Inbox => "inbox",
            Self::Msg => "msg",
            Self::Note => "note",
            Self::User => "user",
            Self::Users => "users",
            Self::Settings => "settings",
            Self::Filter => "filter",
            Self::Clock => "clock",
            Self::History => "history",
            Self::Globe => "globe",
            Self::Target => "target",
            Self::Spark => "spark",
            Self::Zap => "zap",
            Self::Play => "play",
            Self::Copy => "copy",
            Self::Link => "link",
            Self::SideL => "side-l",
            Self::Peek => "peek",
            Self::Split => "split",
            Self::Grid => "grid",
            Self::List => "list",
            Self::More => "more",
            Self::Alert => "alert",
            Self::Info => "info",
            Self::Diamond => "diamond",
            Self::Crown => "crown",
            Self::Heart => "heart",
            Self::Cursor => "cursor",
            Self::Server => "server",
        }
    }

    /// The asset path.
    #[must_use]
    pub const fn path(self) -> &'static str {
        match self {
            Self::Search => "icons/ui/search.svg",
            Self::Orbit => "icons/ui/orbit.svg",
            Self::Package => "icons/ui/package.svg",
            Self::Layers => "icons/ui/layers.svg",
            Self::Trail => "icons/ui/trail.svg",
            Self::Rose => "icons/ui/rose.svg",
            Self::Mosaic => "icons/ui/mosaic.svg",
            Self::Comb => "icons/ui/comb.svg",
            Self::Peel => "icons/ui/peel.svg",
            Self::Book => "icons/ui/book.svg",
            Self::File => "icons/ui/file.svg",
            Self::Folder => "icons/ui/folder.svg",
            Self::Seal => "icons/ui/seal.svg",
            Self::ShieldCheck => "icons/ui/shield-check.svg",
            Self::Lock => "icons/ui/lock.svg",
            Self::Key => "icons/ui/key.svg",
            Self::Eye => "icons/ui/eye.svg",
            Self::Pin => "icons/ui/pin.svg",
            Self::Bookmark => "icons/ui/bookmark.svg",
            Self::Tag => "icons/ui/tag.svg",
            Self::Bell => "icons/ui/bell.svg",
            Self::Inbox => "icons/ui/inbox.svg",
            Self::Msg => "icons/ui/msg.svg",
            Self::Note => "icons/ui/note.svg",
            Self::User => "icons/ui/user.svg",
            Self::Users => "icons/ui/users.svg",
            Self::Settings => "icons/ui/settings.svg",
            Self::Filter => "icons/ui/filter.svg",
            Self::Clock => "icons/ui/clock.svg",
            Self::History => "icons/ui/history.svg",
            Self::Globe => "icons/ui/globe.svg",
            Self::Target => "icons/ui/target.svg",
            Self::Spark => "icons/ui/spark.svg",
            Self::Zap => "icons/ui/zap.svg",
            Self::Play => "icons/ui/play.svg",
            Self::Copy => "icons/ui/copy.svg",
            Self::Link => "icons/ui/link.svg",
            Self::SideL => "icons/ui/side-l.svg",
            Self::Peek => "icons/ui/peek.svg",
            Self::Split => "icons/ui/split.svg",
            Self::Grid => "icons/ui/grid.svg",
            Self::List => "icons/ui/list.svg",
            Self::More => "icons/ui/more.svg",
            Self::Alert => "icons/ui/alert.svg",
            Self::Info => "icons/ui/info.svg",
            Self::Diamond => "icons/ui/diamond.svg",
            Self::Crown => "icons/ui/crown.svg",
            Self::Heart => "icons/ui/heart.svg",
            Self::Cursor => "icons/ui/cursor.svg",
            Self::Server => "icons/ui/server.svg",
        }
    }
}

/// The 20 kind marks: hue = family, shape = kind.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, PartialOrd, Ord)]
pub enum Kind {
    /// `module` (namespace)
    Module,
    /// `package` (namespace)
    Package,
    /// `import` (namespace)
    Import,
    /// `unknown` (namespace)
    Unknown,
    /// `struct` (type)
    Struct,
    /// `class` (type)
    Class,
    /// `enum` (type)
    Enum,
    /// `union` (type)
    Union,
    /// `type` (type)
    Type,
    /// `trait` (contract)
    Trait,
    /// `interface` (contract)
    Interface,
    /// `function` (callable)
    Function,
    /// `method` (callable)
    Method,
    /// `constructor` (callable)
    Constructor,
    /// `macro` (callable)
    Macro,
    /// `constant` (value)
    Constant,
    /// `field` (value)
    Field,
    /// `property` (value)
    Property,
    /// `variable` (value)
    Variable,
    /// `variant` (value)
    Variant,
}

impl Kind {
    /// Every kind, in board order (grouped by family).
    pub const ALL: [Self; 20] = [
        Self::Module,
        Self::Package,
        Self::Import,
        Self::Unknown,
        Self::Struct,
        Self::Class,
        Self::Enum,
        Self::Union,
        Self::Type,
        Self::Trait,
        Self::Interface,
        Self::Function,
        Self::Method,
        Self::Constructor,
        Self::Macro,
        Self::Constant,
        Self::Field,
        Self::Property,
        Self::Variable,
        Self::Variant,
    ];

    /// The tooltip name (`struct`, `trait`, …).
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Module => "module",
            Self::Package => "package",
            Self::Import => "import",
            Self::Unknown => "unknown",
            Self::Struct => "struct",
            Self::Class => "class",
            Self::Enum => "enum",
            Self::Union => "union",
            Self::Type => "type",
            Self::Trait => "trait",
            Self::Interface => "interface",
            Self::Function => "function",
            Self::Method => "method",
            Self::Constructor => "constructor",
            Self::Macro => "macro",
            Self::Constant => "constant",
            Self::Field => "field",
            Self::Property => "property",
            Self::Variable => "variable",
            Self::Variant => "variant",
        }
    }

    /// The family, which picks the hue.
    #[must_use]
    pub const fn family(self) -> Family {
        match self {
            Self::Module => Family::Namespace,
            Self::Package => Family::Namespace,
            Self::Import => Family::Namespace,
            Self::Unknown => Family::Namespace,
            Self::Struct => Family::Type,
            Self::Class => Family::Type,
            Self::Enum => Family::Type,
            Self::Union => Family::Type,
            Self::Type => Family::Type,
            Self::Trait => Family::Contract,
            Self::Interface => Family::Contract,
            Self::Function => Family::Callable,
            Self::Method => Family::Callable,
            Self::Constructor => Family::Callable,
            Self::Macro => Family::Callable,
            Self::Constant => Family::Value,
            Self::Field => Family::Value,
            Self::Property => Family::Value,
            Self::Variable => Family::Value,
            Self::Variant => Family::Value,
        }
    }

    /// The asset path.
    #[must_use]
    pub const fn path(self) -> &'static str {
        match self {
            Self::Module => "icons/kind/module.svg",
            Self::Package => "icons/kind/package.svg",
            Self::Import => "icons/kind/import.svg",
            Self::Unknown => "icons/kind/unknown.svg",
            Self::Struct => "icons/kind/struct.svg",
            Self::Class => "icons/kind/class.svg",
            Self::Enum => "icons/kind/enum.svg",
            Self::Union => "icons/kind/union.svg",
            Self::Type => "icons/kind/type.svg",
            Self::Trait => "icons/kind/trait.svg",
            Self::Interface => "icons/kind/interface.svg",
            Self::Function => "icons/kind/function.svg",
            Self::Method => "icons/kind/method.svg",
            Self::Constructor => "icons/kind/constructor.svg",
            Self::Macro => "icons/kind/macro.svg",
            Self::Constant => "icons/kind/constant.svg",
            Self::Field => "icons/kind/field.svg",
            Self::Property => "icons/kind/property.svg",
            Self::Variable => "icons/kind/variable.svg",
            Self::Variant => "icons/kind/variant.svg",
        }
    }
}

/// The 17 modifier marks: a mark with a tooltip, never an uppercase label.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, PartialOrd, Ord)]
pub enum Mod {
    /// `const`: evaluated at compile time
    Const,
    /// `async`: async: returns a future
    Async,
    /// `unsafe`: unsafe: you uphold the invariants
    Unsafe,
    /// `generic`: generic
    Generic,
    /// `static`: static: one for the whole program
    Static,
    /// `crate`: visible inside this crate only
    Crate,
    /// `deprecated`: deprecated since 0.4
    Deprecated,
    /// `abstract`: abstract: you must provide it
    Abstract,
    /// `derived`: derived, no custom logic
    Derived,
    /// `blanket`: arrives through a blanket impl
    Blanket,
    /// `auto`: auto trait: the compiler proves it
    Auto,
    /// `override`: overrides the inherited one
    Override,
    /// `inherited`: inherited, unchanged
    Inherited,
    /// `makes`: no self: makes one or stands alone
    Makes,
    /// `reads`: borrows self: reads only
    Reads,
    /// `changes`: borrows self mutably: changes it
    Changes,
    /// `consumes`: takes self: the value is gone after
    Consumes,
}

impl Mod {
    /// Every modifier, in board order.
    pub const ALL: [Self; 17] = [
        Self::Const,
        Self::Async,
        Self::Unsafe,
        Self::Generic,
        Self::Static,
        Self::Crate,
        Self::Deprecated,
        Self::Abstract,
        Self::Derived,
        Self::Blanket,
        Self::Auto,
        Self::Override,
        Self::Inherited,
        Self::Makes,
        Self::Reads,
        Self::Changes,
        Self::Consumes,
    ];

    /// The short name.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Const => "const",
            Self::Async => "async",
            Self::Unsafe => "unsafe",
            Self::Generic => "generic",
            Self::Static => "static",
            Self::Crate => "crate",
            Self::Deprecated => "deprecated",
            Self::Abstract => "abstract",
            Self::Derived => "derived",
            Self::Blanket => "blanket",
            Self::Auto => "auto",
            Self::Override => "override",
            Self::Inherited => "inherited",
            Self::Makes => "makes",
            Self::Reads => "reads",
            Self::Changes => "changes",
            Self::Consumes => "consumes",
        }
    }

    /// The tooltip sentence, verbatim from the Language board.
    #[must_use]
    pub const fn tooltip(self) -> &'static str {
        match self {
            Self::Const => "evaluated at compile time",
            Self::Async => "async: returns a future",
            Self::Unsafe => "unsafe: you uphold the invariants",
            Self::Generic => "generic",
            Self::Static => "static: one for the whole program",
            Self::Crate => "visible inside this crate only",
            Self::Deprecated => "deprecated since 0.4",
            Self::Abstract => "abstract: you must provide it",
            Self::Derived => "derived, no custom logic",
            Self::Blanket => "arrives through a blanket impl",
            Self::Auto => "auto trait: the compiler proves it",
            Self::Override => "overrides the inherited one",
            Self::Inherited => "inherited, unchanged",
            Self::Makes => "no self: makes one or stands alone",
            Self::Reads => "borrows self: reads only",
            Self::Changes => "borrows self mutably: changes it",
            Self::Consumes => "takes self: the value is gone after",
        }
    }

    /// The voice it speaks in when it warns (amber for `unsafe`, `deprecated`).
    #[must_use]
    pub const fn voice(self) -> Option<Voice> {
        match self {
            Self::Const => None,
            Self::Async => None,
            Self::Unsafe => Some(Voice::Amber),
            Self::Generic => None,
            Self::Static => None,
            Self::Crate => None,
            Self::Deprecated => Some(Voice::Amber),
            Self::Abstract => None,
            Self::Derived => None,
            Self::Blanket => None,
            Self::Auto => None,
            Self::Override => None,
            Self::Inherited => None,
            Self::Makes => None,
            Self::Reads => None,
            Self::Changes => None,
            Self::Consumes => None,
        }
    }

    /// The asset path.
    #[must_use]
    pub const fn path(self) -> &'static str {
        match self {
            Self::Const => "icons/mod/const.svg",
            Self::Async => "icons/mod/async.svg",
            Self::Unsafe => "icons/mod/unsafe.svg",
            Self::Generic => "icons/mod/generic.svg",
            Self::Static => "icons/mod/static.svg",
            Self::Crate => "icons/mod/crate.svg",
            Self::Deprecated => "icons/mod/deprecated.svg",
            Self::Abstract => "icons/mod/abstract.svg",
            Self::Derived => "icons/mod/derived.svg",
            Self::Blanket => "icons/mod/blanket.svg",
            Self::Auto => "icons/mod/auto.svg",
            Self::Override => "icons/mod/override.svg",
            Self::Inherited => "icons/mod/inherited.svg",
            Self::Makes => "icons/mod/makes.svg",
            Self::Reads => "icons/mod/reads.svg",
            Self::Changes => "icons/mod/changes.svg",
            Self::Consumes => "icons/mod/consumes.svg",
        }
    }
}

/// The 14 capability marks (the derive-trait strip).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, PartialOrd, Ord)]
pub enum Cap {
    /// `clone`: `Clone`
    Clone,
    /// `copy`: `Copy`
    Copy,
    /// `eq`: `Eq`
    Eq,
    /// `ord`: `Ord`
    Ord,
    /// `hash`: `Hash`
    Hash,
    /// `debug`: `Debug`
    Debug,
    /// `display`: `Display`
    Display,
    /// `convert`: `From`, `Into`, `ToString`
    Convert,
    /// `thread`: `Send`, `Sync`
    Thread,
    /// `default`: `Default`
    Default,
    /// `serde`: `Serialize`
    Serde,
    /// `iter`: `IntoIterator`
    Iter,
    /// `deref`: `Deref`
    Deref,
    /// `error`: `Error`
    Error,
}

impl Cap {
    /// Every capability, in board order.
    pub const ALL: [Self; 14] = [
        Self::Clone,
        Self::Copy,
        Self::Eq,
        Self::Ord,
        Self::Hash,
        Self::Debug,
        Self::Display,
        Self::Convert,
        Self::Thread,
        Self::Default,
        Self::Serde,
        Self::Iter,
        Self::Deref,
        Self::Error,
    ];

    /// The short caption (`clone`, `serde`, …).
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Clone => "clone",
            Self::Copy => "copy",
            Self::Eq => "eq",
            Self::Ord => "ord",
            Self::Hash => "hash",
            Self::Debug => "debug",
            Self::Display => "display",
            Self::Convert => "convert",
            Self::Thread => "thread",
            Self::Default => "default",
            Self::Serde => "serde",
            Self::Iter => "iter",
            Self::Deref => "deref",
            Self::Error => "error",
        }
    }

    /// The trait(s) it stands for (the tooltip).
    #[must_use]
    pub const fn traits(self) -> &'static str {
        match self {
            Self::Clone => "Clone",
            Self::Copy => "Copy",
            Self::Eq => "Eq",
            Self::Ord => "Ord",
            Self::Hash => "Hash",
            Self::Debug => "Debug",
            Self::Display => "Display",
            Self::Convert => "From, Into, ToString",
            Self::Thread => "Send, Sync",
            Self::Default => "Default",
            Self::Serde => "Serialize",
            Self::Iter => "IntoIterator",
            Self::Deref => "Deref",
            Self::Error => "Error",
        }
    }

    /// The asset path.
    #[must_use]
    pub const fn path(self) -> &'static str {
        match self {
            Self::Clone => "icons/cap/clone.svg",
            Self::Copy => "icons/cap/copy.svg",
            Self::Eq => "icons/cap/eq.svg",
            Self::Ord => "icons/cap/ord.svg",
            Self::Hash => "icons/cap/hash.svg",
            Self::Debug => "icons/cap/debug.svg",
            Self::Display => "icons/cap/display.svg",
            Self::Convert => "icons/cap/convert.svg",
            Self::Thread => "icons/cap/thread.svg",
            Self::Default => "icons/cap/default.svg",
            Self::Serde => "icons/cap/serde.svg",
            Self::Iter => "icons/cap/iter.svg",
            Self::Deref => "icons/cap/deref.svg",
            Self::Error => "icons/cap/error.svg",
        }
    }
}

/// The 7 ecosystems, as their language marks.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash, PartialOrd, Ord)]
pub enum Lang {
    /// Rust (`cargo`)
    Rust,
    /// TypeScript (`npm`)
    Typescript,
    /// Python (`pypi`)
    Python,
    /// Go (`go`)
    Go,
    /// Java (`maven`)
    Java,
    /// C# (`nuget`)
    Csharp,
    /// C++ (`conan`)
    Cpp,
}

impl Lang {
    /// Every ecosystem, in board order.
    pub const ALL: [Self; 7] = [
        Self::Rust,
        Self::Typescript,
        Self::Python,
        Self::Go,
        Self::Java,
        Self::Csharp,
        Self::Cpp,
    ];

    /// The language name.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Rust => "Rust",
            Self::Typescript => "TypeScript",
            Self::Python => "Python",
            Self::Go => "Go",
            Self::Java => "Java",
            Self::Csharp => "C#",
            Self::Cpp => "C++",
        }
    }

    /// The registry caption (`cargo`, `npm`, …).
    #[must_use]
    pub const fn ecosystem(self) -> &'static str {
        match self {
            Self::Rust => "cargo",
            Self::Typescript => "npm",
            Self::Python => "pypi",
            Self::Go => "go",
            Self::Java => "maven",
            Self::Csharp => "nuget",
            Self::Cpp => "conan",
        }
    }

    /// The mark colour the boards use (`0xRRGGBB`).
    #[must_use]
    pub const fn rgb(self) -> u32 {
        match self {
            Self::Rust => 0x00f0_a27a,
            Self::Typescript => 0x007f_b0ff,
            Self::Python => 0x008f_c4ff,
            Self::Go => 0x007f_dcf0,
            Self::Java => 0x00f2_a0a0,
            Self::Csharp => 0x00c6_a6ff,
            Self::Cpp => 0x009d_b4ff,
        }
    }

    /// The asset path.
    #[must_use]
    pub const fn path(self) -> &'static str {
        match self {
            Self::Rust => "icons/lang/rust.svg",
            Self::Typescript => "icons/lang/typescript.svg",
            Self::Python => "icons/lang/python.svg",
            Self::Go => "icons/lang/go.svg",
            Self::Java => "icons/lang/java.svg",
            Self::Csharp => "icons/lang/csharp.svg",
            Self::Cpp => "icons/lang/cpp.svg",
        }
    }
}
