[package]
name = "nudox-workflow"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nudox-id = { path = "../nudox-id" }
nudox-object = { path = "../nudox-object" }
nudox-observe = { path = "../nudox-observe" }
nudox-runtime = { path = "../nudox-runtime" }
nudox-schema = { path = "../nudox-schema" }
strum.workspace = true
thiserror.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
