[package]
name = "backend-compile"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
backend-version = { path = "../version" }
backend-flow = { path = "../flow" }
backend-semantic = { path = "../semantic" }
tree-sitter.workspace = true
blake3.workspace = true

[lints]
workspace = true
