//! The `rmcp` server: the eight §L6 tools plus the §L6 resource set.
//!
//! This module is the MCP *surface*. Every tool body immediately delegates to
//! the matching `NudoxTools::do_*` method in [`crate::tools`], which is where
//! the engine calls live. The split exists so that a tool's behaviour can be
//! tested without a transport, and so that `#[tool_router]`'s expansion does
//! not sit on top of the logic.
//!
//! # Tool descriptions are documentation
//!
//! A description string here is the *only* documentation an LLM client ever
//! sees for a tool — there is no README, no rustdoc, and no type signature it
//! can read. Each one therefore says what the tool returns, when to prefer it
//! over the others, and what a `SymbolKey` looks like. The typed tools
//! (`search_symbols`, `get_symbol`, `find_usages`, `list_packages`,
//! `list_versions`, `select_version`) announce themselves as the first choice
//! and `graph_query` announces itself as the escape hatch, per §L6.
//!
//! # Resources
//!
//! §L6 asks for "the schema, and one resource per loaded package":
//!
//! * `nudox://schema` — the Trustfall SDL, identical to what `graph_schema`
//!   returns. It is a resource *as well as* a tool because MCP clients attach
//!   resources up front, which is exactly when an agent needs the schema —
//!   before it writes its first `graph_query`.
//! * `nudox://package/{ecosystem}:{name}` — one per loaded package, resolved
//!   through the same engine call `list_packages` uses (LR-8). There is no
//!   second path to the corpus.

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::wrapper::{Json, Parameters};
use rmcp::model::{
    Implementation, ListResourcesResult, PaginatedRequestParams, ProtocolVersion,
    ReadResourceRequestParams, ReadResourceResult, Resource, ResourceContents, ServerCapabilities,
    ServerInfo,
};
use rmcp::service::RequestContext;
use rmcp::{ErrorData, RoleServer, ServerHandler, tool, tool_handler, tool_router};

use crate::error::McpError;
use crate::tools::{
    DiffVersionsArgs, DiffVersionsResult, FindUsagesArgs, GetSymbolArgs, GraphQueryArgs,
    GraphSchemaArgs, ListPackagesArgs, ListVersionsArgs, ListVersionsResult, NudoxTools,
    PackagesResult, QueryResult, SchemaResult, SearchResult, SearchSymbolsArgs, SelectVersionArgs,
    SelectVersionResult, SymbolDoc, UsagesResult,
};

/// URI of the schema resource.
pub const SCHEMA_URI: &str = "nudox://schema";

/// URI prefix of the per-package resources.
pub const PACKAGE_URI_PREFIX: &str = "nudox://package/";

/// Instructions surfaced to the MCP client at initialisation.
///
/// The one place an agent is told how the tools relate to each other before it
/// has called any of them, so it says which to reach for first.
const INSTRUCTIONS: &str = "\
Local documentation and code intelligence for the packages loaded in this nudox \
workspace. Every answer comes from IR produced on this machine or verified \
against a remote generation, and carries a `provenance` field saying which.

Start with `list_packages` to see what is loaded, then `search_symbols` to find \
a symbol by name, then `get_symbol` to read it in full. Use `find_usages` to \
find a symbol's callers. All four speak the same key format, \
`ecosystem:name#introhex`, so a key returned by one goes straight into another. \
`get_symbol`'s result also carries `timeline`: the symbol's history across \
every loaded version of its package (renames, deprecations, signature changes, \
introduction, removal).

When a package has more than one version loaded, use `list_versions` to see \
them and `select_version` to switch which one the other tools answer from. \
Most `SymbolKey`s survive a version switch, but not all — read \
`select_version`'s description before relying on one across a switch.

Reach for `graph_query` only when those tools cannot express the question. It \
runs an arbitrary Trustfall query over the corpus, and you must call \
`graph_schema` first to learn the exact type, property and edge names.";

/// The MCP server `lindsey` hosts (§L6).
///
/// `Clone` because rmcp builds one instance per MCP session; the clone is two
/// `Arc` bumps and a shared route table.
#[derive(Clone)]
pub struct NudoxMcpServer {
    /// The engine-backed tool logic (LR-8).
    tools: NudoxTools,
    /// The rmcp route table, generated by `#[tool_router]`.
    tool_router: ToolRouter<Self>,
}

impl std::fmt::Debug for NudoxMcpServer {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("NudoxMcpServer").finish_non_exhaustive()
    }
}

impl NudoxMcpServer {
    /// Build a server over an already-started engine.
    pub fn new(engine: nudox_engine::EngineHandle) -> Self {
        Self::from_tools(NudoxTools::new(engine))
    }

    /// Build a server over an existing tool set.
    pub fn from_tools(tools: NudoxTools) -> Self {
        Self {
            tools,
            tool_router: Self::tool_router(),
        }
    }

    /// The tool set this server exposes.
    pub fn tools(&self) -> &NudoxTools {
        &self.tools
    }

    /// Every resource this server serves right now.
    ///
    /// Recomputed per call rather than cached: packages load asynchronously
    /// after start-up (LR-10 paints before the data arrives), so a cached list
    /// would report an empty workspace forever to a client that connected
    /// during seeding.
    async fn resources(&self) -> Result<Vec<Resource>, McpError> {
        let mut resources = vec![
            Resource::new(SCHEMA_URI, "Trustfall schema")
                .with_title("nudox graph schema")
                .with_description(
                    "The GraphQL SDL that `graph_query` queries are validated against. \
Read this before writing a query.",
                )
                .with_mime_type("application/graphql"),
        ];

        for pkg in self.tools.do_list_packages().await?.packages {
            resources.push(
                Resource::new(
                    format!("{PACKAGE_URI_PREFIX}{}", pkg.lineage),
                    pkg.name.clone(),
                )
                .with_title(pkg.lineage.clone())
                .with_description(format!(
                    "Package {} from the {} ecosystem. Its lineage key `{}` prefixes every \
symbol key it declares, and is what `search_symbols`'s `packages` filter accepts.",
                    pkg.name, pkg.ecosystem, pkg.lineage
                ))
                .with_mime_type("application/json"),
            );
        }

        Ok(resources)
    }
}

// ---------------------------------------------------------------------------
// Tools
// ---------------------------------------------------------------------------

#[tool_router(router = tool_router)]
impl NudoxMcpServer {
    /// Find symbols by name or kind across the loaded corpus.
    #[tool(
        name = "search_symbols",
        description = "PREFER THIS FIRST when looking for a symbol by name. Searches the \
loaded local corpus by symbol name and by kind, returning ranked hits — each with its stable \
key, rendered signature (as text and as typed tokens), kind, trust provenance and relevance \
score. A key looks like `ecosystem:name#introhex`, for example \
`cargo:serde#3f1a…` with 64 hex characters after the `#`; pass it straight to `get_symbol` to \
read the symbol or to `find_usages` to find its callers. Narrow with `kinds` (Function, Record, \
Trait, Enum, Impl, Alias, Field, Const, Static, Module, Variant, Reexport, Param) and with \
`packages` (each `ecosystem:name`; see `list_packages`). This matches names and kinds, not \
documentation prose — for structural questions such as \"which types implement this trait\" or \
\"what does this function reference\", use `graph_query`. Results are paginated: if `next_cursor` \
is present in the response, more results exist — pass it back as `cursor` to get the next page. \
Treat `cursor` as opaque; never construct one yourself."
    )]
    pub async fn search_symbols(
        &self,
        Parameters(args): Parameters<SearchSymbolsArgs>,
    ) -> Result<Json<SearchResult>, ErrorData> {
        Ok(Json(self.tools.do_search(args).await?))
    }

    /// Read one symbol's full documentation page.
    #[tool(
        name = "get_symbol",
        description = "PREFER THIS to read a symbol once you have its key. Returns one symbol's \
complete documentation page: its signature (as text and as typed tokens whose type references \
carry the key of the symbol they resolve to), its breadcrumb path, visibility, any deprecation \
notice, its trust provenance, and every rendered section — prose, examples, code blocks, member \
lists and field lists — in reading order. `key` must be `ecosystem:name#introhex` as returned by \
`search_symbols`, `find_usages` or `graph_query`; it is the same key everywhere. This is the \
highest-fidelity view of a single symbol and is always better than reassembling one from \
`graph_query` properties."
    )]
    pub async fn get_symbol(
        &self,
        Parameters(args): Parameters<GetSymbolArgs>,
    ) -> Result<Json<SymbolDoc>, ErrorData> {
        Ok(Json(self.tools.do_get_symbol(args).await?))
    }

    /// Find the symbols that reference a given symbol.
    #[tool(
        name = "find_usages",
        description = "PREFER THIS to answer \"who calls this?\" or \"what breaks if I change \
this?\". Given a symbol key, returns the symbols holding a resolved reference to it — callers of \
a function, users of a type — each with its own key, name and kind, so you can follow the chain \
with `get_symbol`. Only references the producer resolved with index-grade confidence or better \
are returned, so results are precise rather than textual: a name that merely appears in a comment \
or belongs to an unrelated identifier will not show up. `key` must be `ecosystem:name#introhex`. \
Paginated the same way as `search_symbols`: check `next_cursor` and pass it back as `cursor` for \
more."
    )]
    pub async fn find_usages(
        &self,
        Parameters(args): Parameters<FindUsagesArgs>,
    ) -> Result<Json<UsagesResult>, ErrorData> {
        Ok(Json(self.tools.do_find_usages(args).await?))
    }

    /// List the packages currently loaded.
    #[tool(
        name = "list_packages",
        description = "PREFER THIS FIRST to discover what is available before searching. Returns \
every package loaded into the local corpus with its `ecosystem:name` lineage key, display name \
and ecosystem. The lineage key prefixes every symbol key in that package and is exactly what \
`search_symbols`'s `packages` filter accepts. If a package you expect is missing then it has not \
been produced or loaded yet and no other tool will find symbols from it — this is how you tell \
\"not indexed here\" apart from \"does not exist\"."
    )]
    pub async fn list_packages(
        &self,
        Parameters(_args): Parameters<ListPackagesArgs>,
    ) -> Result<Json<PackagesResult>, ErrorData> {
        Ok(Json(self.tools.do_list_packages().await?))
    }

    /// List every loaded generation of a package.
    #[tool(
        name = "list_versions",
        description = "List every loaded generation of one package, newest first, with which one \
is current and its symbol count. Several real packages in this corpus have more than one version \
loaded at once (for example memchr, pydantic, guava, jackson-databind) — call this to see them \
before assuming there is only one. `package` is `ecosystem:name` (see `list_packages`). An unloaded \
package returns zero versions rather than an error. HONESTY NOTE: most symbol keys are stable \
across the versions this lists, but not all are — some declarations mint a key that depends on \
byte offsets or emission order and does not survive every release. This tool cannot tell you which \
ones in a given package are affected; see `select_version`'s description before switching."
    )]
    pub async fn list_versions(
        &self,
        Parameters(args): Parameters<ListVersionsArgs>,
    ) -> Result<Json<ListVersionsResult>, ErrorData> {
        Ok(Json(self.tools.do_list_versions(args).await?))
    }

    /// Switch which loaded generation of a package the other tools answer from.
    #[tool(
        name = "select_version",
        description = "Switch which loaded generation of a package `get_symbol`, `search_symbols` \
and `graph_query` answer from. `package` is `ecosystem:name`; `version` must be one of the strings \
`list_versions` returned — call that first. Returns `Switched` (with the new symbol count) or, if \
the version is not loaded, `NotLoaded` — not an error, since the engine only holds what it was \
asked to load. By the time you receive this tool's response the switch has actually landed, so \
subsequent calls answer from the new generation. HONESTY NOTE, read before relying on this across a \
switch: most `SymbolKey`s survive a version change unchanged, because their identity is derived \
from the declaration's content — but not every declaration's key is content-derived. Some fall back \
to an identity keyed on byte offset or emission order during lowering, and that kind of key can \
silently stop resolving after a switch — indistinguishable from the symbol having been deleted, \
because this tool has no way to tell you in advance which declarations in a package are affected. \
If a key you held before switching returns `symbol not found` afterward, treat it as possibly-stale \
and re-fetch it with `search_symbols` rather than concluding the symbol was removed."
    )]
    pub async fn select_version(
        &self,
        Parameters(args): Parameters<SelectVersionArgs>,
    ) -> Result<Json<SelectVersionResult>, ErrorData> {
        Ok(Json(self.tools.do_select_version(args).await?))
    }

    /// Compare two loaded generations of one package.
    #[tool(
        name = "diff_versions",
        description = "Compare two loaded generations of one package and get back what changed, \
declaration by declaration — the question `select_version` could previously only answer by \
switching, querying, switching back and diffing by hand. `package` is `ecosystem:name`; \
`from_version` is the OLDER and `to_version` the NEWER, exactly as `list_versions` spells them \
(call it first; several packages here have two generations loaded). If either is not loaded you \
get `not_loaded` with the list of ones that are, not an error. READ THE VERDICT ON EACH ROW: \
`removed` is the ONLY value that means a declaration is gone, and it is emitted only when the \
symbol's key was derived from its own content. `rekeyed` means one declaration got a new key \
(use `to_key`, stop using `from_key`) — a naive diff would report that as a deletion plus an \
addition, which is the single most misleading thing a diff can say. `indeterminate` means it \
vanished but its key was of a kind that can move on its own, so the tool refuses to guess: \
re-search by name and path before concluding it was deleted. Rows are paginated like \
`search_symbols`; the counts describe the whole diff on every page."
    )]
    pub async fn diff_versions(
        &self,
        Parameters(args): Parameters<DiffVersionsArgs>,
    ) -> Result<Json<DiffVersionsResult>, ErrorData> {
        Ok(Json(self.tools.do_diff_versions(args).await?))
    }

    /// Run an arbitrary Trustfall query over the corpus.
    #[tool(
        name = "graph_query",
        description = "THE ESCAPE HATCH — use it only when the typed tools cannot express the \
question. `search_symbols`, `get_symbol`, `find_usages`, `list_packages`, `list_versions` and \
`select_version` are faster, cheaper and better shaped for what they cover; come here for \
structural or relational questions they do not, such as \"every public function in package X \
returning type Y\" (the `returnedBy` edge), \"what does this type implement\" (`implementedBy`), \
\"all implementors of this trait\" (`implementors`), or a join across packages. Takes a \
Trustfall (GraphQL-subset) query plus string variable bindings referenced as `$name`, and returns \
column names with positionally aligned string cells, so `rows[i].cells[j]` is the value of \
`columns[j]`. ALWAYS call `graph_schema` first and write the query against the exact type, \
property and edge names it returns — queries are validated against that schema, so a guessed \
field name is an error rather than an empty result. Paginated the same way as `search_symbols`: \
check `next_cursor` and pass it back as `cursor` for more."
    )]
    pub async fn graph_query(
        &self,
        Parameters(args): Parameters<GraphQueryArgs>,
    ) -> Result<Json<QueryResult>, ErrorData> {
        Ok(Json(self.tools.do_graph_query(args).await?))
    }

    /// Return the Trustfall schema `graph_query` is checked against.
    #[tool(
        name = "graph_schema",
        description = "Returns, verbatim, the GraphQL SDL schema that `graph_query` queries are \
validated against. Call this before writing any `graph_query`: it documents every queryable type \
(Package; Symbol and its Function, Record, Trait, Impl, Enum, Field, Const and Alias \
implementors; Occurrence), every scalar property, every edge (members, parent, usages, mentions, \
implementors, occurrencesOf, and the type-reference edges implementedBy, subtypes, returnedBy, \
acceptedBy, heldBy and signatureTypes) and the cost of each traversal. It also documents the \
`ecosystem:name#introhex` key format that every other tool consumes. The schema is fixed for the \
life of the server, so one call per session is enough."
    )]
    pub async fn graph_schema(
        &self,
        Parameters(_args): Parameters<GraphSchemaArgs>,
    ) -> Result<Json<SchemaResult>, ErrorData> {
        Ok(Json(SchemaResult {
            schema: crate::SCHEMA_SDL.to_owned(),
        }))
    }
}

// ---------------------------------------------------------------------------
// ServerHandler
// ---------------------------------------------------------------------------

#[tool_handler(router = self.tool_router)]
impl ServerHandler for NudoxMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_resources()
                .build(),
        )
        .with_protocol_version(ProtocolVersion::LATEST)
        .with_server_info(Implementation::from_build_env())
        .with_instructions(INSTRUCTIONS)
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, ErrorData> {
        Ok(ListResourcesResult::with_all_items(self.resources().await?))
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, ErrorData> {
        let uri = request.uri;

        if uri == SCHEMA_URI {
            return Ok(ReadResourceResult::new(vec![ResourceContents::text(
                crate::SCHEMA_SDL,
                &uri,
            )]));
        }

        if let Some(lineage) = uri.strip_prefix(PACKAGE_URI_PREFIX) {
            let packages = self.tools.do_list_packages().await?;
            let found = packages
                .packages
                .into_iter()
                .find(|p| p.lineage == lineage)
                .ok_or_else(|| McpError::UnknownResource(uri.clone()))?;
            let body = serde_json::to_string_pretty(&found).map_err(|e| {
                ErrorData::internal_error(format!("failed to encode package resource: {e}"), None)
            })?;
            return Ok(ReadResourceResult::new(vec![ResourceContents::text(
                body, &uri,
            )]));
        }

        Err(McpError::UnknownResource(uri).into())
    }
}
