# Provisions the real seven-language fleet corpus from pinned sources.
#
# Every package coordinate in the fleet manifest resolves to a fixed-output
# fetch (hashes recorded in `corpus-pins.json`, generated by prefetching the
# exact manifest coordinates) plus two workspace-local Rust crates.  Lane
# roots below match the directory layouts the corpus resolver admits:
#   rust:       <root>/<name>-<version>            (crates.io .crate archives)
#   typescript: <root>/<name>-<version>            (npm tarballs, versioned so
#                same-named versions coexist; the resolver prefers exact names)
#   python:     <root>/<name>-<version>            (PyPI sdists, wheels staged)
#   go:         <root>/<module>@<version>          (module proxy zips)
#   java:       <root>/<group-path>/<artifact>/<version>  (Maven sources jars)
#   csharp:     <root>/<id>/<version>              (NuGet packages, .cs kept)
#   clang:      <root>/<Project>                   (pinned project trees)
#
# Each lane root verifies at build time that every manifest coordinate owns
# a directory holding at least one lane source file.  A missing or empty
# package fails the build loudly; absence can never become a silent skip.
{
  pkgs,
  workspaceRoot,
}:
let
  workspaceAvailable = builtins.pathExists (workspaceRoot + "/Cargo.toml");
  pins = builtins.fromJSON (builtins.readFile ./corpus-pins.json);

  pinsFor = lane: builtins.filter (pin: pin.lane == lane) pins;

  # Splits `ecosystem:name@version` into its parts. The name keeps embedded
  # colons (Maven `group:artifact`) and slashes (Go modules, npm scopes);
  # the version is everything after the final `@`.
  parsePurl =
    coordinate:
    let
      parts = builtins.match "([^:]+):(.*)@([^@]*)" coordinate;
    in
    assert parts != null;
    {
      ecosystem = builtins.elemAt parts 0;
      name = builtins.elemAt parts 1;
      version = builtins.elemAt parts 2;
    };

  # Workspace-local Rust crates named by their manifest coordinates.
  localCrateDir =
    coordinate:
    let
      name = (parsePurl coordinate).name;
      stem = pkgs.lib.removePrefix "backend-" name;
    in
    "crates/${stem}";

  # The lane-root-relative directory one coordinate must own.
  packageDir =
    lane: coordinate:
    if lane == "clang" then
      coordinate
    else
      let
        parts = parsePurl coordinate;
      in
      if lane == "rust" || lane == "typescript" || lane == "python" then
        "${parts.name}-${parts.version}"
      else if lane == "go" then
        "${parts.name}@${parts.version}"
      else if lane == "csharp" then
        "${parts.name}/${parts.version}"
      else if lane == "java" then
        let
          groups = builtins.match "([^:]+):([^:]+)" parts.name;
          group = builtins.elemAt groups 0;
          artifact = builtins.elemAt groups 1;
        in
        "${pkgs.lib.replaceStrings [ "." ] [ "/" ] group}/${artifact}/${parts.version}"
      else
        throw "unknown corpus lane ${lane}";

  laneExtensionFind =
    lane:
    if lane == "rust" then
      ''-name "*.rs"''
    else if lane == "typescript" then
      ''\( -name "*.ts" -o -name "*.tsx" -o -name "*.d.mts" -o -name "*.d.cts" \)''
    else if lane == "python" then
      ''-name "*.py"''
    else if lane == "go" then
      ''-name "*.go"''
    else if lane == "java" then
      ''-name "*.java"''
    else if lane == "csharp" then
      ''-name "*.cs"''
    else if lane == "clang" then
      ''\( -name "*.c" -o -name "*.h" -o -name "*.cc" -o -name "*.cpp" -o -name "*.cxx" -o -name "*.hpp" \)''
    else
      throw "unknown corpus lane ${lane}";

  fetchedSource =
    pin:
    if pin.kind == "local" then
      null
    else
      pkgs.fetchurl {
        url = pin.url;
        hash = pin.hash;
      };

  # Workspace-local crate sources, materialized into the store so builds
  # stay pure and hermetic.
  localCrateSource =
    coordinate:
    builtins.path {
      path = workspaceRoot + "/${localCrateDir coordinate}";
      name = "fleet-corpus-local-${(parsePurl coordinate).name}";
    };

  # Shell block unpacking one package beneath $out/<dir>. Every branch
  # fails loudly when the archive layout is not what the lane expects.
  unpackBlock =
    lane: pin:
    let
      dir = packageDir lane pin.coordinate;
      src = fetchedSource pin;
    in
    if pin.kind == "local" then
      ''
        mkdir -p "$out/${dir}"
        cp -r ${localCrateSource pin.coordinate}/. "$out/${dir}/"
      ''
    else if pin.kind == "crate" then
      ''
        mkdir -p "$out"
        tar -xzf ${src} -C "$out"
        if [ ! -d "$out/${dir}" ]; then
          echo "corpus: crate archive for ${pin.coordinate} did not produce ${dir}" >&2
          exit 1
        fi
      ''
    else if lane == "typescript" then
      ''
        rm -rf "$work/unpack"
        mkdir -p "$work/unpack" "$out/${dir}"
        tar -xzf ${src} -C "$work/unpack"
        if [ -d "$work/unpack/package" ]; then
          cp -r "$work/unpack/package/." "$out/${dir}/"
        elif [ "$(find "$work/unpack" -mindepth 1 -maxdepth 1 | wc -l)" -eq 1 ]; then
          cp -r "$work/unpack/"*"/." "$out/${dir}/"
        else
          echo "corpus: npm archive for ${pin.coordinate} has no single package root" >&2
          exit 1
        fi
      ''
    else if lane == "python" then
      ''
        rm -rf "$work/unpack"
        mkdir -p "$work/unpack" "$out/${dir}"
        tar -xzf ${src} -C "$work/unpack"
        tops=$(find "$work/unpack" -mindepth 1 -maxdepth 1 | wc -l)
        if [ "$tops" -eq 1 ]; then
          cp -r "$work/unpack/"*"/." "$out/${dir}/"
        else
          mkdir -p "$out/${dir}/dist"
          cp -r "$work/unpack/." "$out/${dir}/dist/"
        fi
      ''
    else if pin.kind == "gomod" then
      ''
        mkdir -p "$out"
        ${pkgs.unzip}/bin/unzip -q -o ${src} -d "$out"
        if [ ! -d "$out/${dir}" ]; then
          echo "corpus: module zip for ${pin.coordinate} did not produce ${dir}" >&2
          exit 1
        fi
      ''
    else if pin.kind == "jarsrc" || pin.kind == "nupkg" then
      ''
        mkdir -p "$out/${dir}"
        ${pkgs.unzip}/bin/unzip -q -o ${src} -d "$out/${dir}"
      ''
    else if lane == "clang" then
      (
        if pkgs.lib.hasSuffix ".zip" pin.url then
          ''
            rm -rf "$work/unpack"
            mkdir -p "$work/unpack"
            ${pkgs.unzip}/bin/unzip -q -o ${src} -d "$work/unpack"
          ''
        else
          ''
            rm -rf "$work/unpack"
            mkdir -p "$work/unpack"
            tar -xzf ${src} -C "$work/unpack"
          ''
      )
      + ''
        tops=$(find "$work/unpack" -mindepth 1 -maxdepth 1 | wc -l)
        if [ "$tops" -ne 1 ]; then
          echo "corpus: project archive for ${pin.coordinate} has $tops top-level entries" >&2
          exit 1
        fi
        mkdir -p "$out"
        mv "$work/unpack/"* "$out/${dir}"
      ''
    else
      throw "unknown corpus archive kind ${pin.kind}";

  # Shell block failing loudly when a coordinate owns no lane sources.
  verifyBlock =
    lane: pin:
    let
      dir = packageDir lane pin.coordinate;
    in
    ''
      if [ ! -d "$out/${dir}" ]; then
        echo "corpus: missing directory $out/${dir} for ${pin.coordinate}" >&2
        exit 1
      fi
      if [ -z "$(find "$out/${dir}" -type f ${laneExtensionFind lane} -print -quit)" ]; then
        echo "corpus: no ${lane} sources under $out/${dir} for ${pin.coordinate}" >&2
        exit 1
      fi
    '';

  laneRoot =
    lane:
    pkgs.runCommand "fleet-corpus-${lane}"
      {
        buildInputs = [
          pkgs.gnutar
          pkgs.gzip
          pkgs.unzip
        ];
      }
      ''
        set -e
        work=$(mktemp -d)
        trap 'rm -rf "$work"' EXIT
        ${builtins.concatStringsSep "\n" (map (unpackBlock lane) (pinsFor lane))}
        ${builtins.concatStringsSep "\n" (map (verifyBlock lane) (pinsFor lane))}
      '';

  lanes = [
    "rust"
    "typescript"
    "python"
    "go"
    "java"
    "csharp"
    "clang"
  ];
in
if workspaceAvailable then
  builtins.listToAttrs (
    map (lane: {
      name = lane;
      value = laneRoot lane;
    }) lanes
  )
else
  null
