[package]
name = "nudox-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
atomic-waker.workspace = true
loom = { version = "0.7", optional = true }
nudox-observe = { path = "../nudox-observe" }
thiserror.workspace = true

[dev-dependencies]

[features]
loom-model = ["dep:loom"]

[lints]
workspace = true
