[package]
name = "server-index-ingest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
backend-semantic = { path = "../semantic" }
server-index-vocabulary = { path = "../server-index-vocabulary" }

[lib]
path = "lib.rs"

[dev-dependencies]
backend-version = { path = "../version" }
