[package]
name = "server-index-ingest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
compiler-ir = { path = "../../../compiler/ir" }
server-index-vocabulary = { path = "../vocabulary" }

[lib]
path = "lib.rs"

[dev-dependencies]
heart-identity = { path = "../../../heart/identity" }
