//! Registry calling conventions, one row per product command.
//!
//! Lookup stays in the parent module. This table is the single answer those
//! lookups search.

use super::{ArgumentKind, ArgumentSpec, CommandGrammar};

const LIMIT: ArgumentSpec = ArgumentSpec::optional(
    "limit",
    ArgumentKind::Limit,
    "Maximum rows in this page, 1 to 200.",
);

/// The calling convention of every registry row, in registry order.
pub const GRAMMARS: [CommandGrammar; 40] = [
    CommandGrammar {
        name: "advisory",
        tool: "backend.advisory",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "package",
            ArgumentKind::PackageReference,
            "A pinned purl or an exact local package label.",
        )],
        options: &[
            ArgumentSpec::optional(
                "override-actor",
                ArgumentKind::Text,
                "Auditable actor identity for an exceptional allow.",
            ),
            ArgumentSpec::optional(
                "override-reason",
                ArgumentKind::Text,
                "Why the blocked release is being reviewed.",
            ),
            ArgumentSpec::optional(
                "override-policy-version",
                ArgumentKind::Text,
                "Positive policy version that granted the override.",
            ),
            ArgumentSpec::optional(
                "override-expires-at",
                ArgumentKind::Text,
                "Optional Unix timestamp at which the override expires.",
            ),
        ],
        when: "Use before adding a package to inspect source IDs, aliases, affected and fixed ranges, freshness, coverage, and the typed acquisition decision.",
    },
    CommandGrammar {
        name: "packages",
        tool: "backend.packages",
        aliases: &["projects-indexed"],
        positional: &[],
        options: &[],
        when: "Call this first in a new session: it is the only way to learn which project roots exist and whether each one is ready to answer.",
    },
    CommandGrammar {
        name: "add",
        tool: "backend.index",
        aliases: &["index"],
        positional: &[ArgumentSpec::optional(
            "path",
            ArgumentKind::ProjectPath,
            "Project directory; defaults to the active project.",
        )],
        options: &[],
        when: "Use when packages does not list the project you need, or when its source changed since the last revision.",
    },
    CommandGrammar {
        name: "remove",
        tool: "backend.remove",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "path",
            ArgumentKind::ProjectPath,
            "Project directory to drop from the shelf.",
        )],
        options: &[],
        when: "Use to stop answering from a project you no longer read; its derived indexes go with it.",
    },
    CommandGrammar {
        name: "show",
        tool: "backend.document",
        aliases: &["document"],
        positional: &[ArgumentSpec::required(
            "coordinate",
            ArgumentKind::Coordinate,
            "Exact declaration coordinate from a search or outline result.",
        )],
        options: &[],
        when: "Reach for this immediately after search: it is the cheapest complete answer about one declaration.",
    },
    CommandGrammar {
        name: "source",
        tool: "backend.source",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "coordinate",
            ArgumentKind::Coordinate,
            "Exact declaration coordinate from a search or outline result.",
        )],
        options: &[],
        when: "Use when the signature and documentation are not enough and you need the code itself.",
    },
    CommandGrammar {
        name: "related",
        tool: "backend.related",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "coordinate",
            ArgumentKind::Coordinate,
            "Exact declaration coordinate to centre the neighbourhood on.",
        )],
        options: &[],
        when: "Use after you have a coordinate to see callers and callees in this package. Package-level dependents are a separate call.",
    },
    CommandGrammar {
        name: "references",
        tool: "backend.references",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "coordinate",
            ArgumentKind::Coordinate,
            "Exact declaration coordinate whose uses are requested.",
        )],
        options: &[],
        when: "Use to answer where is this symbol used: every row carries the relation kind, the authority class, and the exact source span that proves the use.",
    },
    CommandGrammar {
        name: "read",
        tool: "backend.read",
        aliases: &[],
        positional: &[ArgumentSpec::repeated(
            "coordinate",
            ArgumentKind::Coordinate,
            "Exact declaration coordinates; each is answered or refused on its own.",
        )],
        options: &[],
        when: "Use instead of several show calls when you already know every coordinate you need.",
    },
    CommandGrammar {
        name: "diff",
        tool: "backend.diff",
        aliases: &[],
        positional: &[
            ArgumentSpec::required(
                "from",
                ArgumentKind::PackageReference,
                "Older package: a pinned purl or an exact local package label.",
            ),
            ArgumentSpec::required(
                "to",
                ArgumentKind::PackageReference,
                "Newer package: a pinned purl or an exact local package label.",
            ),
        ],
        options: &[],
        when: "Use to answer what changed between two versions without reading either one end to end.",
    },
    CommandGrammar {
        name: "outline",
        tool: "backend.outline",
        aliases: &[],
        positional: &[ArgumentSpec::optional(
            "path",
            ArgumentKind::ProjectPath,
            "Project directory; defaults to the active project.",
        )],
        options: &[],
        when: "Use to learn a package's shape before searching it, when you do not yet know what to search for.",
    },
    CommandGrammar {
        name: "resolve",
        tool: "backend.resolve",
        aliases: &["name"],
        positional: &[ArgumentSpec::required(
            "query",
            ArgumentKind::Text,
            "A readable declaration name or address.",
        )],
        options: &[LIMIT],
        when: "Use when you have a name from prose or a stack trace and need the exact coordinates it could mean.",
    },
    CommandGrammar {
        name: "search",
        tool: "backend.search",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "query",
            ArgumentKind::Text,
            "Text to find in names, signatures, and documentation.",
        )],
        options: &[LIMIT],
        when: "Start here for a question like where error handling lives. Match names, signatures, and documentation, then open a coordinate.",
    },
    CommandGrammar {
        name: "graph",
        tool: "backend.graph",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "coordinate",
            ArgumentKind::Coordinate,
            "Exact declaration coordinate to traverse from.",
        )],
        options: &[],
        when: "Use to follow one declaration outward along calls and references in its package.",
    },
    CommandGrammar {
        name: "health",
        tool: "backend.status",
        aliases: &["status"],
        positional: &[],
        options: &[],
        when: "Check this before trusting an empty result: it says which capabilities are ready and which are simply not configured.",
    },
    CommandGrammar {
        name: "explore",
        tool: "backend.explore",
        aliases: &[],
        positional: &[ArgumentSpec::optional(
            "query",
            ArgumentKind::Text,
            "Case-insensitive filter; omit to browse everything.",
        )],
        options: &[LIMIT],
        when: "Use to browse the package registries rather than the compiled shelf.",
    },
    CommandGrammar {
        name: "package",
        tool: "backend.package",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "package",
            ArgumentKind::PackageReference,
            "A pinned purl or an exact local package label.",
        )],
        options: &[],
        when: "Use to decide whether to depend on a package before adding it to the shelf.",
    },
    CommandGrammar {
        name: "dependents",
        tool: "backend.dependents",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "package",
            ArgumentKind::PackageReference,
            "A pinned purl or an exact local package label.",
        )],
        options: &[],
        when: "Use to judge how widely a package is relied on before changing or replacing it.",
    },
    CommandGrammar {
        name: "dependencies",
        tool: "backend.dependencies",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "package",
            ArgumentKind::PackageReference,
            "A pinned purl or an exact local package label.",
        )],
        options: &[],
        when: "Use to inspect the requirements and scopes declared by one package.",
    },
    CommandGrammar {
        name: "owner",
        tool: "backend.owner",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "owner",
            ArgumentKind::Text,
            "Registry publisher handle.",
        )],
        options: &[],
        when: "Use to find the rest of a publisher's work when one of their packages already fits.",
    },
    CommandGrammar {
        name: "index-search",
        tool: "backend.index_search",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "query",
            ArgumentKind::Text,
            "Name prefix or term.",
        )],
        options: &[LIMIT],
        when: "Use for a name-first lookup across every package the local registry index knows, indexed or not.",
    },
    CommandGrammar {
        name: "package-versions",
        tool: "backend.package_versions",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "package",
            ArgumentKind::PackageReference,
            "A pinned purl or an exact local package label.",
        )],
        options: &[],
        when: "Use to pick an exact version to pin, with its checksum and yanked state.",
    },
    CommandGrammar {
        name: "semantic-versions",
        tool: "backend.semantic_versions",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "package",
            ArgumentKind::PackageReference,
            "A pinned purl or an exact local package label.",
        )],
        options: &[],
        when: "Use before select-semantic-version to see which compiler generations were retained.",
    },
    CommandGrammar {
        name: "select-semantic-version",
        tool: "backend.select_semantic_version",
        aliases: &[],
        positional: &[
            ArgumentSpec::required(
                "package",
                ArgumentKind::PackageReference,
                "A pinned purl or an exact local package label.",
            ),
            ArgumentSpec::required(
                "coordinate",
                ArgumentKind::PackageCoordinate,
                "Exact compiler purl for the target language lane.",
            ),
            ArgumentSpec::required(
                "profile",
                ArgumentKind::LanguageProfile,
                "Closed source language and dialect profile.",
            ),
            ArgumentSpec::required(
                "generation",
                ArgumentKind::Generation,
                "Immutable generation identity, 64 hexadecimal digits.",
            ),
        ],
        options: &[],
        when: "Use to pin answers to one exact compiler generation when a newer one disagrees.",
    },
    CommandGrammar {
        name: "package-profile",
        tool: "backend.package_profile",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "package",
            ArgumentKind::PackageReference,
            "A pinned purl or an exact local package label.",
        )],
        options: &[],
        when: "Use for the one-call summary of a package: its newest version and how many exist.",
    },
    CommandGrammar {
        name: "subscribe",
        tool: "backend.subscribe",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "package",
            ArgumentKind::PackageReference,
            "A pinned purl or an exact local package label.",
        )],
        options: &[ArgumentSpec::optional(
            "project",
            ArgumentKind::ProjectSelector,
            "Project folder to file the subscription into.",
        )],
        when: "Use to be told about new releases instead of re-checking a package by hand.",
    },
    CommandGrammar {
        name: "unsubscribe",
        tool: "backend.unsubscribe",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "package",
            ArgumentKind::PackageReference,
            "A pinned purl or an exact local package label.",
        )],
        options: &[],
        when: "Use to stop following a package without deleting the project folder it sat in.",
    },
    CommandGrammar {
        name: "subscriptions",
        tool: "backend.subscriptions",
        aliases: &[],
        positional: &[],
        options: &[],
        when: "Use to see everything you follow and how much of it you have not looked at.",
    },
    CommandGrammar {
        name: "releases",
        tool: "backend.releases",
        aliases: &[],
        positional: &[],
        options: &[ArgumentSpec::optional(
            "mark-seen",
            ArgumentKind::Flag,
            "Mark the returned newest releases as seen.",
        )],
        when: "Use as the periodic check on followed packages; pass mark-seen only when you have acted on the list.",
    },
    CommandGrammar {
        name: "projects",
        tool: "backend.projects",
        aliases: &[],
        positional: &[],
        options: &[],
        when: "Use to see the project folders that group subscriptions, with their lockfile bindings.",
    },
    CommandGrammar {
        name: "project-create",
        tool: "backend.project_create",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "name",
            ArgumentKind::ProjectName,
            "Unique project folder name, at most 64 bytes.",
        )],
        options: &[ArgumentSpec::optional(
            "lockfile",
            ArgumentKind::LockfilePath,
            "Absolute supported lockfile the folder stays in sync with.",
        )],
        when: "Use to group packages that belong to one piece of work, optionally driven by a lockfile.",
    },
    CommandGrammar {
        name: "project-delete",
        tool: "backend.project_delete",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "project",
            ArgumentKind::ProjectSelector,
            "Project folder by identity or unique name.",
        )],
        options: &[],
        when: "Use when a piece of work is finished; the subscriptions it held survive.",
    },
    CommandGrammar {
        name: "project-add",
        tool: "backend.project_add",
        aliases: &[],
        positional: &[
            ArgumentSpec::required(
                "project",
                ArgumentKind::ProjectSelector,
                "Project folder by identity or unique name.",
            ),
            ArgumentSpec::required(
                "package",
                ArgumentKind::PackageReference,
                "Pinned package to file into the folder.",
            ),
        ],
        options: &[],
        when: "Use to put one pinned package into a folder you already created.",
    },
    CommandGrammar {
        name: "project-remove",
        tool: "backend.project_remove",
        aliases: &[],
        positional: &[
            ArgumentSpec::required(
                "project",
                ArgumentKind::ProjectSelector,
                "Project folder by identity or unique name.",
            ),
            ArgumentSpec::required(
                "package",
                ArgumentKind::PackageReference,
                "Pinned package to take out of the folder.",
            ),
        ],
        options: &[],
        when: "Use to take one package out of a folder without unsubscribing from it.",
    },
    CommandGrammar {
        name: "project-sync",
        tool: "backend.project_sync",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "project",
            ArgumentKind::ProjectSelector,
            "Project folder by identity or unique name.",
        )],
        options: &[],
        when: "Use after the bound lockfile changed, to make the folder match it again.",
    },
    CommandGrammar {
        name: "tree",
        tool: "backend.tree",
        aliases: &[],
        positional: &[],
        options: &[],
        when: "Use to see what a person has open in the desktop or another session before you change it.",
    },
    CommandGrammar {
        name: "tree-open",
        tool: "backend.tree_open",
        aliases: &[],
        positional: &[
            ArgumentSpec::required(
                "subject",
                ArgumentKind::SubjectKind,
                "Which kind of subject to open.",
            ),
            ArgumentSpec::required("value", ArgumentKind::Text, "The subject's operand."),
        ],
        options: &[
            ArgumentSpec::optional("parent", ArgumentKind::NodeId, "Parent node to nest under."),
            ArgumentSpec::optional("title", ArgumentKind::Text, "Short node title."),
        ],
        when: "Use to put what you found in front of the person who asked, in the surface they are already looking at.",
    },
    CommandGrammar {
        name: "tree-close",
        tool: "backend.tree_close",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "node",
            ArgumentKind::NodeId,
            "Session tree node identity.",
        )],
        options: &[ArgumentSpec::optional(
            "branch",
            ArgumentKind::Flag,
            "Close the node's descendants too.",
        )],
        when: "Use to tidy the shared tree when a line of work is done.",
    },
    CommandGrammar {
        name: "forge-add",
        tool: "backend.forge_add",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "coordinate",
            ArgumentKind::ForgeCoordinate,
            "HTTPS forge repository URL with an explicit tag, branch, or commit; append #subdir for a monorepo package.",
        )],
        options: &[],
        when: "Use to acquire a project or package that is absent from the configured registries.",
    },
    CommandGrammar {
        name: "forge-reference",
        tool: "backend.forge_reference",
        aliases: &[],
        positional: &[ArgumentSpec::required(
            "coordinate",
            ArgumentKind::ForgeCoordinate,
            "The exact forge coordinate previously acquired into the local cache.",
        )],
        options: &[],
        when: "Use offline or during restart to read an exact source snapshot from the local cache.",
    },
];
