[package]
name = "backend-store-s3"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
test-support = []

[dependencies]
backend-store = { path = "../store" }
base64.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
ureq.workspace = true

[dev-dependencies]
backend-version = { path = "../version" }

[lints]
workspace = true
