//! Deterministic local source resolution for the frozen package inventory.
//!
//! This module owns only package-layout lookup and source-byte selection.  It
//! never downloads, searches outside the lane root, follows symlinked
//! directories, or substitutes generated bytes for a missing package.

use super::*;

const MAX_SOURCE_TREE_DEPTH: usize = 64;
const MAX_SOURCE_DIRECTORY_ENTRIES: usize = 16 * 1024;
const MAX_SOURCE_FILE_CANDIDATES: usize = 16 * 1024;

enum SourceTraversalError {
    Io(io::Error),
    TreeTooDeep,
    DirectoryEntryCountExceeded,
    FileCountExceeded,
}

/// Resolve one package only below its lane root. The directory naming rules
/// match the existing language test-support layouts; no network or unrelated
/// filesystem walk is permitted.
pub(super) fn resolve_package_source(
    case: RealPackageCase,
) -> Result<ResolvedPackageSource, SourceUnavailableCause> {
    let SourceRoot::Environment {
        variable,
        relative,
        layout,
        extension,
    } = case.root;
    let Some(root) = std::env::var_os(variable).map(PathBuf::from) else {
        return Err(source_unavailable(
            case.language,
            SourceUnavailableKind::RootUnset,
        ));
    };
    let root = root.join(relative);
    let package_root = package_root(&root, case.coordinate, layout).ok_or_else(|| {
        source_unavailable(
            case.language,
            SourceUnavailableKind::PackageDirectoryMissing,
        )
    })?;
    let path = largest_source_file(&package_root, extension, case.language)?;
    let byte_len = fs::metadata(&path)
        .map_err(|_| source_unavailable(case.language, SourceUnavailableKind::ReadFailure))?
        .len();
    if byte_len > REAL_SOURCE_BYTE_LIMIT {
        return Err(source_unavailable(
            case.language,
            SourceUnavailableKind::SourceTooLarge,
        ));
    }
    let bytes = fs::read(&path)
        .map_err(|_| source_unavailable(case.language, SourceUnavailableKind::ReadFailure))?;
    let identity = source_identity(&bytes);
    Ok(ResolvedPackageSource {
        coordinate: case.coordinate,
        language: case.language,
        profile: case.profile,
        table: case.table,
        source_root: root,
        path,
        bytes,
        identity,
        authority: AuthorityProvenance::Unresolved {
            tool: native_tool(case.language),
        },
    })
}

fn source_unavailable(
    language: CorpusLanguage,
    kind: SourceUnavailableKind,
) -> SourceUnavailableCause {
    SourceUnavailableCause { language, kind }
}

fn coordinate_parts(coordinate: PackageCoordinate) -> Option<(&'static str, &'static str)> {
    let raw = match coordinate {
        PackageCoordinate::Purl(value) => value.split_once(':')?.1,
        PackageCoordinate::Project(_) => return None,
    };
    let (name, version) = raw.rsplit_once('@')?;
    (!name.is_empty() && !version.is_empty()).then_some((name, version))
}

fn package_root(
    root: &Path,
    coordinate: PackageCoordinate,
    layout: PackageLayout,
) -> Option<PathBuf> {
    match layout {
        PackageLayout::CargoRegistry => {
            let (name, version) = coordinate_parts(coordinate)?;
            let stem = format!("{name}-{version}");
            let direct = root.join(&stem);
            if direct.is_dir() {
                return Some(direct);
            }
            let mut index_roots = fs::read_dir(root)
                .ok()?
                .filter_map(Result::ok)
                .map(|entry| entry.path())
                .filter(|path| path.is_dir())
                .collect::<Vec<_>>();
            index_roots.sort();
            index_roots
                .into_iter()
                .map(|path| path.join(&stem))
                .find(|path| path.is_dir())
        }
        PackageLayout::NodeModules => {
            let (name, _) = coordinate_parts(coordinate)?;
            let direct = root.join(name);
            if direct.is_dir() {
                Some(direct)
            } else {
                let nested = root.join("node_modules").join(name);
                nested.is_dir().then_some(nested)
            }
        }
        PackageLayout::PythonDistribution => {
            let (name, version) = coordinate_parts(coordinate)?;
            let direct = root.join(format!("{name}-{version}"));
            direct.is_dir().then_some(direct)
        }
        PackageLayout::GoModule => {
            let (name, version) = coordinate_parts(coordinate)?;
            let direct = root.join(format!("{name}@{version}"));
            direct.is_dir().then_some(direct)
        }
        PackageLayout::MavenSource => {
            let (name, version) = coordinate_parts(coordinate)?;
            let mut path = root.to_owned();
            for component in name.split(':') {
                if component.is_empty() {
                    return None;
                }
                path.push(component);
            }
            path.push(version);
            path.is_dir().then_some(path)
        }
        PackageLayout::NugetSource => {
            let (name, version) = coordinate_parts(coordinate)?;
            let direct = root.join(name).join(version);
            direct.is_dir().then_some(direct)
        }
        PackageLayout::ClangProject => {
            let PackageCoordinate::Project(name) = coordinate else {
                return None;
            };
            let direct = root.join(name);
            direct.is_dir().then_some(direct)
        }
    }
}

fn largest_source_file(
    root: &Path,
    extension: SourceExtension,
    language: CorpusLanguage,
) -> Result<PathBuf, SourceUnavailableCause> {
    let mut files = Vec::new();
    collect_source_files(root, extension, &mut files, 0).map_err(|error| {
        let kind = match error {
            SourceTraversalError::Io(_) => SourceUnavailableKind::ReadFailure,
            SourceTraversalError::TreeTooDeep => SourceUnavailableKind::SourceTreeTooDeep,
            SourceTraversalError::DirectoryEntryCountExceeded => {
                SourceUnavailableKind::SourceDirectoryEntryCountExceeded
            }
            SourceTraversalError::FileCountExceeded => {
                SourceUnavailableKind::SourceFileCountExceeded
            }
        };
        source_unavailable(language, kind)
    })?;
    files.sort_by(|left, right| right.1.cmp(&left.1).then_with(|| left.0.cmp(&right.0)));
    files
        .into_iter()
        .next()
        .map(|(path, _)| path)
        .ok_or_else(|| source_unavailable(language, SourceUnavailableKind::SourceFileMissing))
}

fn collect_source_files(
    root: &Path,
    extension: SourceExtension,
    files: &mut Vec<(PathBuf, u64)>,
    depth: usize,
) -> Result<(), SourceTraversalError> {
    if depth > MAX_SOURCE_TREE_DEPTH {
        return Err(SourceTraversalError::TreeTooDeep);
    }
    let mut entries = Vec::new();
    let mut directory = fs::read_dir(root).map_err(SourceTraversalError::Io)?;
    while let Some(entry) = directory.next() {
        if entries.len() >= MAX_SOURCE_DIRECTORY_ENTRIES {
            return Err(SourceTraversalError::DirectoryEntryCountExceeded);
        }
        entries.push(entry.map_err(SourceTraversalError::Io)?);
    }
    entries.sort_by_key(|entry| entry.path());
    for entry in entries {
        let path = entry.path();
        let file_type = entry.file_type().map_err(SourceTraversalError::Io)?;
        if file_type.is_dir() {
            collect_source_files(&path, extension, files, depth + 1)?;
        } else if file_type.is_file() && extension.accepts(&path) {
            if files.len() >= MAX_SOURCE_FILE_CANDIDATES {
                return Err(SourceTraversalError::FileCountExceeded);
            }
            let length = entry.metadata().map_err(SourceTraversalError::Io)?.len();
            files.push((path, length));
        }
    }
    Ok(())
}
