load("//build:rust.bzl", "crate", "deps", "member", "rust_crate")

rust_crate(
    name = "protocol",
    deps = deps([
        member("heart"),
        member("ir"),
        crate("serde", features = ["derive"]),
        crate("postcard", features = ["alloc"]),
        crate("bytes"),
        crate("smol_str"),
        crate("thiserror"),
    ]),
)
