[package]
name = "nudox-compile-driver"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nudox-compile-vocab = { path = "../nudox-compile-vocab" }
nudox-ir-format = { path = "../nudox-ir-format" }
nudox-ir-vocab = { path = "../nudox-ir-vocab" }
nudox-id = { path = "../nudox-id" }
thiserror.workspace = true
