[package]
name = "wave-application-mcp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "wave-application-mcp"
path = "src/main.rs"

[dependencies]
serde_json.workspace = true
wave-application-core = { path = "../wave-application-core" }
wave-application-protocol = { path = "../wave-application-protocol" }

[lints]
workspace = true
