load("//build:rust.bzl", "crate", "deps", "rust_crate", "rust_tests", "target")

rust_crate(
    name = "heart",
    srcs = native.glob(["**/*.rs"], exclude = ["tests/**"]),
    deps = deps([
        crate("uuid"),
        crate("semver"),
        crate("tower"),
        crate("nutype"),
        crate("strum"),
        crate("postcard"),
        crate("uv_pep440"),
        crate("serde"),
        crate("thiserror"),
        crate("blake3"),
        crate("smol_str"),
        crate("compact_str"),
        crate("chrono"),
        crate("ordered_float"),
        crate("data_encoding"),
        crate("url"),
        crate("anyhow"),
    ]),
)

rust_tests(
    prefix = "test",
    deps = deps([
        crate("uuid"),
        crate("semver"),
        crate("tower"),
        crate("tokio"),
        target(":heart"),
    ]),
)
