[package]
name = "heart"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[dependencies]
uuid = { workspace = true }
semver = { workspace = true }
tower = { workspace = true }
nutype = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
blake3 = { workspace = true }
smol_str = { workspace = true }
compact_str = { workspace = true }
chrono = { workspace = true }
ordered-float = { workspace = true }
strum = { workspace = true }
data-encoding = { workspace = true }
postcard = { workspace = true }
uv-pep440 = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
proptest = { workspace = true }
insta = { workspace = true }
semver = { workspace = true }
