[package]
name = "backend-local-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
backend-compile = { path = "../compile" }
backend-engine = { path = "../engine" }
backend-extension-turso = { path = "../../extensions/turso" }
backend-frontend-clang = { path = "../../frontends/clang" }
backend-frontend-csharp = { path = "../../frontends/csharp" }
backend-frontend-go = { path = "../../frontends/go" }
backend-frontend-java = { path = "../../frontends/java" }
backend-frontend-python = { path = "../../frontends/python" }
backend-frontend-rust = { path = "../../frontends/rust" }
backend-frontend-typescript = { path = "../../frontends/typescript" }
backend-runtime = { path = "../runtime" }
futures-executor.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[lints]
workspace = true
