load("//build:rust.bzl", "crate", "deps", "member", "rust_crate", "rust_tests", "target")

rust_crate(
    name = "cas",
    deps = deps([
        member("heart"),
        member("caching"),
        crate("bytes"),
        crate("thiserror"),
        crate("blake3"),
        crate("tokio"),
        crate("tracing"),
    ]),
)

rust_tests(
    prefix = "test",
    deps = deps([
        crate("tokio"),
        crate("tempfile"),
        crate("bytes"),
        target(":cas"),
    ]),
)
