//! Attempt-scoped read observation broker used for diagnostics only.
//!
//! This module records events from explicitly registered producers. Sealing
//! confirms producer-local sequence/count consistency; it does not certify
//! complete compiler read coverage or authorize work reuse.

use crate::compiler_attempt_v2::CompilationAttemptId;
use crate::compiler_input_tree_v2::MAX_TREE_RECORDS;

const MAX_READ_OBSERVATION_BYTES: u64 = 512 * 1024 * 1024;
const READ_OBSERVATION_DOMAIN: &[u8] = b"backend.compiler.read-observation.v2\0";

/// Independent observation channels required before a future Rust adapter
/// could attempt to establish a complete compiler read frontier.
///
/// These channels are intentionally more granular than the current RA
/// observations. Sealing them proves only that registered producers closed their
/// event streams; it does not prove that a producer observed every read.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
#[repr(u8)]
pub(crate) enum CompilerReadObservationChannelV2 {
    /// Exact selected editor buffers installed in RA's database.
    EditorOverlay = 0,
    /// Positive file buffers resident in the RA VFS after workspace loading.
    RaVfsLoader = 1,
    /// Positive and negative Rust module-resolution candidates.
    RustModuleResolver = 2,
    /// Other authority filesystem probes, including failed metadata/open calls.
    AuthorityFilesystem = 3,
    /// Complete direct-child sets and errors from directory enumeration.
    DirectoryEnumeration = 4,
    /// Cargo manifest discovery, metadata, config, and project-model reads.
    CargoProjectModel = 5,
    /// Present and absent environment values consulted by the authority.
    Environment = 6,
    /// Executable identity, arguments, output, and lifecycle for every child.
    ProcessTree = 7,
    /// Rust toolchain, rustup, sysroot, and standard-library inputs.
    ToolchainSysroot = 8,
    /// Build-script or other generated bytes consumed by the authority.
    GeneratedOutputs = 9,
    /// Registry, path dependency, and other external source inputs.
    ExternalDependencies = 10,
}

impl CompilerReadObservationChannelV2 {
    const ALL: [Self; 11] = [
        Self::EditorOverlay,
        Self::RaVfsLoader,
        Self::RustModuleResolver,
        Self::AuthorityFilesystem,
        Self::DirectoryEnumeration,
        Self::CargoProjectModel,
        Self::Environment,
        Self::ProcessTree,
        Self::ToolchainSysroot,
        Self::GeneratedOutputs,
        Self::ExternalDependencies,
    ];

    const fn index(self) -> usize {
        self as usize
    }

    const fn label(self) -> &'static str {
        match self {
            Self::EditorOverlay => "editor_overlay",
            Self::RaVfsLoader => "ra_vfs_loader",
            Self::RustModuleResolver => "rust_module_resolver",
            Self::AuthorityFilesystem => "authority_filesystem",
            Self::DirectoryEnumeration => "directory_enumeration",
            Self::CargoProjectModel => "cargo_project_model",
            Self::Environment => "environment",
            Self::ProcessTree => "process_tree",
            Self::ToolchainSysroot => "toolchain_sysroot",
            Self::GeneratedOutputs => "generated_outputs",
            Self::ExternalDependencies => "external_dependencies",
        }
    }
}

/// Closed event classes accepted by the attempt-scoped diagnostic recorder.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub(crate) enum CompilerReadObservationEventClassV2 {
    /// Exact selected editor-overlay bytes.
    EditorBuffer = 1,
    /// A positive filesystem or VFS file input observation.
    PresentFile = 2,
    /// A failed lookup whose absence can affect compilation.
    AbsentPath = 3,
    /// A complete directory enumeration result.
    DirectoryListing = 4,
    /// A present or absent environment-variable observation.
    EnvironmentValue = 5,
    /// A Cargo/project-model observation.
    CargoProject = 6,
    /// One child process identity, output, or lifecycle event.
    ChildProcess = 7,
    /// A toolchain or sysroot input.
    ToolchainInput = 8,
    /// A generated output input.
    GeneratedOutput = 9,
    /// An external dependency input.
    ExternalInput = 10,
    /// A Rust module-resolution candidate or membership result.
    ModuleResolution = 11,
    /// The producer encountered a read class outside its declared contract.
    Unsupported = 255,
}

/// Why a diagnostic observation attempt could not seal its producer set.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum CompilerReadObservationFailureV2 {
    /// A producer was registered more than once.
    DuplicateProducer,
    /// A token was forged, stale, or belongs to another attempt.
    StaleAttemptOrProducer,
    /// The producer sequence was not contiguous.
    SequenceGap,
    /// The producer's independent terminal count disagreed with delivered events.
    FinalCountMismatch,
    /// The event class did not belong to its registered channel.
    UnsupportedReadClass,
    /// The bounded event or byte budget was exceeded.
    Limit,
    /// A path supplied to a path-bearing event was not portable and canonical.
    UnsupportedPath,
}

/// Attempt-local token issued only by [`CompilerReadObservationRecorderV2`].
#[derive(Clone, Copy, Debug)]
pub(crate) struct CompilerReadObservationProducerV2 {
    attempt_id: CompilationAttemptId,
    channel: CompilerReadObservationChannelV2,
}

struct CompilerReadObservationChannelStateV2 {
    registered: bool,
    sealed: bool,
    next_sequence: u64,
    transcript: blake3::Hasher,
}

impl CompilerReadObservationChannelStateV2 {
    fn new(attempt_id: CompilationAttemptId, channel: CompilerReadObservationChannelV2) -> Self {
        let mut transcript = blake3::Hasher::new();
        transcript.update(READ_OBSERVATION_DOMAIN);
        attempt_id.update_hasher(&mut transcript);
        transcript.update(&[channel as u8]);
        Self {
            registered: false,
            sealed: false,
            next_sequence: 0,
            transcript,
        }
    }
}

/// Single-owner, bounded event broker for one diagnostic compiler attempt.
///
/// It retains only per-channel rolling transcripts and counters, not an event
/// allocation per read. Producers are registered and drained synchronously by
/// the owning compiler lane. A future child-process broker may merge events
/// only after child termination and must seal with an independently obtained
/// final count. This recorder never mints `VerifiedUnitReadClosure` and is not
/// a trust-registry entry.
pub(crate) struct CompilerReadObservationRecorderV2 {
    attempt_id: CompilationAttemptId,
    channels: [CompilerReadObservationChannelStateV2; 11],
    failure: Option<CompilerReadObservationFailureV2>,
    event_count: u64,
    byte_count: u64,
}

/// Bounded administrative report about producer registration and event delivery.
///
/// `all_required_producers_sealed` means only that each known producer token
/// reported a terminal count. It is not a statement that compiler reads were
/// completely observed.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct CompilerReadObservationReportV2 {
    attempt_counter: u64,
    registered_channels: usize,
    sealed_channels: usize,
    required_channels: usize,
    events: u64,
    bytes: u64,
    failure: Option<CompilerReadObservationFailureV2>,
    missing_channels: Vec<CompilerReadObservationChannelV2>,
    unsealed_channels: Vec<CompilerReadObservationChannelV2>,
    transcript_digest: [u8; 32],
}

impl CompilerReadObservationReportV2 {
    pub(crate) const fn attempt_counter(&self) -> u64 {
        self.attempt_counter
    }

    pub(crate) const fn registered_channels(&self) -> usize {
        self.registered_channels
    }

    pub(crate) const fn sealed_channels(&self) -> usize {
        self.sealed_channels
    }

    pub(crate) const fn required_channels(&self) -> usize {
        self.required_channels
    }

    pub(crate) const fn events(&self) -> u64 {
        self.events
    }

    pub(crate) const fn bytes(&self) -> u64 {
        self.bytes
    }

    pub(crate) const fn failure(&self) -> Option<CompilerReadObservationFailureV2> {
        self.failure
    }

    pub(crate) const fn transcript_digest(&self) -> [u8; 32] {
        self.transcript_digest
    }

    pub(crate) fn all_required_producers_sealed(&self) -> bool {
        self.failure.is_none()
            && self.registered_channels == self.required_channels
            && self.sealed_channels == self.required_channels
            && self.missing_channels.is_empty()
            && self.unsealed_channels.is_empty()
    }

    pub(crate) fn missing_channel_labels(&self) -> Vec<&'static str> {
        self.missing_channels
            .iter()
            .chain(&self.unsealed_channels)
            .copied()
            .map(CompilerReadObservationChannelV2::label)
            .collect()
    }
}

impl CompilerReadObservationRecorderV2 {
    pub(crate) fn new(attempt: CompilationAttemptId) -> Self {
        let attempt_id = attempt;
        Self {
            attempt_id,
            channels: std::array::from_fn(|index| {
                CompilerReadObservationChannelStateV2::new(
                    attempt_id,
                    CompilerReadObservationChannelV2::ALL[index],
                )
            }),
            failure: None,
            event_count: 0,
            byte_count: 0,
        }
    }

    pub(crate) fn register(
        &mut self,
        channel: CompilerReadObservationChannelV2,
    ) -> Result<CompilerReadObservationProducerV2, CompilerReadObservationFailureV2> {
        self.check_healthy()?;
        let state = &mut self.channels[channel.index()];
        if state.registered {
            return self.poison(CompilerReadObservationFailureV2::DuplicateProducer);
        }
        state.registered = true;
        Ok(CompilerReadObservationProducerV2 {
            attempt_id: self.attempt_id,
            channel,
        })
    }

    pub(crate) fn observe_editor_buffer(
        &mut self,
        producer: &CompilerReadObservationProducerV2,
        sequence: u64,
        relative_path: &str,
        contents: &[u8],
    ) -> Result<(), CompilerReadObservationFailureV2> {
        self.check_healthy()?;
        if producer.channel != CompilerReadObservationChannelV2::EditorOverlay {
            return self.poison(CompilerReadObservationFailureV2::UnsupportedReadClass);
        }
        if relative_path.is_empty()
            || crate::compiler_input_manifest_v2::validate_compiler_input_path_v2(relative_path)
                .is_err()
        {
            return self.poison(CompilerReadObservationFailureV2::UnsupportedPath);
        }
        if producer.attempt_id != self.attempt_id
            || producer.channel != CompilerReadObservationChannelV2::EditorOverlay
        {
            return self.poison(CompilerReadObservationFailureV2::StaleAttemptOrProducer);
        }
        let state = &self.channels[producer.channel.index()];
        if !state.registered || state.sealed {
            return self.poison(CompilerReadObservationFailureV2::StaleAttemptOrProducer);
        }
        if sequence != state.next_sequence {
            return self.poison(CompilerReadObservationFailureV2::SequenceGap);
        }
        if self.event_count >= MAX_TREE_RECORDS as u64 {
            return self.poison(CompilerReadObservationFailureV2::Limit);
        }
        let byte_charge = u64::try_from(contents.len()).unwrap_or(u64::MAX);
        if self
            .byte_count
            .checked_add(byte_charge)
            .is_none_or(|total_bytes| total_bytes > MAX_READ_OBSERVATION_BYTES)
        {
            return self.poison(CompilerReadObservationFailureV2::Limit);
        }
        let content_digest = blake3::hash(contents);
        let mut identity = blake3::Hasher::new();
        identity.update(b"backend.compiler.editor-buffer-observation.v2\0");
        identity.update(&(relative_path.len() as u32).to_be_bytes());
        identity.update(relative_path.as_bytes());
        identity.update(&byte_charge.to_be_bytes());
        identity.update(content_digest.as_bytes());
        self.observe_digest(
            producer,
            sequence,
            CompilerReadObservationEventClassV2::EditorBuffer,
            *identity.finalize().as_bytes(),
            byte_charge,
        )
    }

    /// Records one canonical path-bearing observation. The path is included
    /// in the transcript identity, and unsupported spellings poison the
    /// attempt before it can be sealed.
    pub(crate) fn observe_path_event(
        &mut self,
        producer: &CompilerReadObservationProducerV2,
        sequence: u64,
        class: CompilerReadObservationEventClassV2,
        path: &str,
        evidence_digest: [u8; 32],
        byte_charge: u64,
    ) -> Result<(), CompilerReadObservationFailureV2> {
        self.check_healthy()?;
        if !matches!(
            class,
            CompilerReadObservationEventClassV2::PresentFile
                | CompilerReadObservationEventClassV2::AbsentPath
                | CompilerReadObservationEventClassV2::DirectoryListing
                | CompilerReadObservationEventClassV2::ModuleResolution
                | CompilerReadObservationEventClassV2::ToolchainInput
                | CompilerReadObservationEventClassV2::GeneratedOutput
                | CompilerReadObservationEventClassV2::ExternalInput
        ) {
            return self.poison(CompilerReadObservationFailureV2::UnsupportedReadClass);
        }
        if path.is_empty()
            || crate::compiler_input_manifest_v2::validate_compiler_input_path_v2(path).is_err()
        {
            return self.poison(CompilerReadObservationFailureV2::UnsupportedPath);
        }
        if evidence_digest == [0; 32] {
            return self.poison(CompilerReadObservationFailureV2::UnsupportedReadClass);
        }
        let mut identity = blake3::Hasher::new();
        identity.update(b"backend.compiler.path-observation.v2\0");
        identity.update(&[class as u8]);
        identity.update(&(path.len() as u32).to_be_bytes());
        identity.update(path.as_bytes());
        identity.update(&evidence_digest);
        self.observe_digest(
            producer,
            sequence,
            class,
            *identity.finalize().as_bytes(),
            byte_charge,
        )
    }

    /// Records a path-bearing event when the source is a native absolute path
    /// that must not be retained or passed through the portable manifest path
    /// validator. Both path identity and evidence are reduced to digests by
    /// the caller; this remains diagnostic and does not prove path coverage.
    pub(crate) fn observe_opaque_path_event(
        &mut self,
        producer: &CompilerReadObservationProducerV2,
        sequence: u64,
        class: CompilerReadObservationEventClassV2,
        path_identity_digest: [u8; 32],
        evidence_digest: [u8; 32],
        byte_charge: u64,
    ) -> Result<(), CompilerReadObservationFailureV2> {
        self.check_healthy()?;
        if !matches!(
            class,
            CompilerReadObservationEventClassV2::PresentFile
                | CompilerReadObservationEventClassV2::AbsentPath
                | CompilerReadObservationEventClassV2::ModuleResolution
                | CompilerReadObservationEventClassV2::ToolchainInput
                | CompilerReadObservationEventClassV2::GeneratedOutput
                | CompilerReadObservationEventClassV2::ExternalInput
        ) || path_identity_digest == [0; 32]
            || evidence_digest == [0; 32]
        {
            return self.poison(CompilerReadObservationFailureV2::UnsupportedReadClass);
        }
        let mut identity = blake3::Hasher::new();
        identity.update(b"backend.compiler.opaque-path-observation.v2\0");
        identity.update(&[class as u8]);
        identity.update(&path_identity_digest);
        identity.update(&evidence_digest);
        self.observe_digest(
            producer,
            sequence,
            class,
            *identity.finalize().as_bytes(),
            byte_charge,
        )
    }

    /// Records an environment, project-model, or process event whose exact
    /// identity has already been encoded by its channel adapter.
    pub(crate) fn observe_nonpath_event(
        &mut self,
        producer: &CompilerReadObservationProducerV2,
        sequence: u64,
        class: CompilerReadObservationEventClassV2,
        evidence_digest: [u8; 32],
        byte_charge: u64,
    ) -> Result<(), CompilerReadObservationFailureV2> {
        self.check_healthy()?;
        if !matches!(
            class,
            CompilerReadObservationEventClassV2::EnvironmentValue
                | CompilerReadObservationEventClassV2::CargoProject
                | CompilerReadObservationEventClassV2::ChildProcess
        ) || evidence_digest == [0; 32]
        {
            return self.poison(CompilerReadObservationFailureV2::UnsupportedReadClass);
        }
        let mut identity = blake3::Hasher::new();
        identity.update(b"backend.compiler.nonpath-observation.v2\0");
        identity.update(&[class as u8]);
        identity.update(&evidence_digest);
        self.observe_digest(
            producer,
            sequence,
            class,
            *identity.finalize().as_bytes(),
            byte_charge,
        )
    }

    fn observe_digest(
        &mut self,
        producer: &CompilerReadObservationProducerV2,
        sequence: u64,
        class: CompilerReadObservationEventClassV2,
        identity: [u8; 32],
        byte_charge: u64,
    ) -> Result<(), CompilerReadObservationFailureV2> {
        self.check_healthy()?;
        if producer.attempt_id != self.attempt_id {
            return self.poison(CompilerReadObservationFailureV2::StaleAttemptOrProducer);
        }
        if !class_matches_channel(class, producer.channel) {
            return self.poison(CompilerReadObservationFailureV2::UnsupportedReadClass);
        }
        if class == CompilerReadObservationEventClassV2::Unsupported || identity == [0; 32] {
            return self.poison(CompilerReadObservationFailureV2::UnsupportedReadClass);
        }
        let state = &mut self.channels[producer.channel.index()];
        if !state.registered || state.sealed {
            return self.poison(CompilerReadObservationFailureV2::StaleAttemptOrProducer);
        }
        if sequence != state.next_sequence {
            return self.poison(CompilerReadObservationFailureV2::SequenceGap);
        }
        if self.event_count >= MAX_TREE_RECORDS as u64 {
            return self.poison(CompilerReadObservationFailureV2::Limit);
        }
        let Some(total_bytes) = self.byte_count.checked_add(byte_charge) else {
            return self.poison(CompilerReadObservationFailureV2::Limit);
        };
        if total_bytes > MAX_READ_OBSERVATION_BYTES {
            return self.poison(CompilerReadObservationFailureV2::Limit);
        }
        let Some(next_sequence) = state.next_sequence.checked_add(1) else {
            return self.poison(CompilerReadObservationFailureV2::Limit);
        };
        state.transcript.update(&sequence.to_be_bytes());
        state.transcript.update(&[class as u8]);
        state.transcript.update(&identity);
        state.transcript.update(&byte_charge.to_be_bytes());
        state.next_sequence = next_sequence;
        self.event_count = self.event_count.saturating_add(1);
        self.byte_count = total_bytes;
        Ok(())
    }

    pub(crate) fn seal(
        &mut self,
        producer: &CompilerReadObservationProducerV2,
        final_event_count: u64,
    ) -> Result<(), CompilerReadObservationFailureV2> {
        self.check_healthy()?;
        if producer.attempt_id != self.attempt_id {
            return self.poison(CompilerReadObservationFailureV2::StaleAttemptOrProducer);
        }
        let state = &mut self.channels[producer.channel.index()];
        if !state.registered || state.sealed {
            return self.poison(CompilerReadObservationFailureV2::StaleAttemptOrProducer);
        }
        if final_event_count != state.next_sequence {
            return self.poison(CompilerReadObservationFailureV2::FinalCountMismatch);
        }
        state.sealed = true;
        Ok(())
    }

    pub(crate) fn report(&self) -> CompilerReadObservationReportV2 {
        let mut missing_channels = Vec::new();
        let mut unsealed_channels = Vec::new();
        let mut registered_channels = 0;
        let mut sealed_channels = 0;
        let mut transcript = blake3::Hasher::new();
        transcript.update(READ_OBSERVATION_DOMAIN);
        self.attempt_id.update_hasher(&mut transcript);
        for channel in CompilerReadObservationChannelV2::ALL {
            let state = &self.channels[channel.index()];
            transcript.update(&[channel as u8]);
            transcript.update(&[u8::from(state.registered), u8::from(state.sealed)]);
            transcript.update(&state.next_sequence.to_be_bytes());
            transcript.update(state.transcript.clone().finalize().as_bytes());
            if !state.registered {
                missing_channels.push(channel);
            } else {
                registered_channels += 1;
                if state.sealed {
                    sealed_channels += 1;
                } else {
                    unsealed_channels.push(channel);
                }
            }
        }
        CompilerReadObservationReportV2 {
            attempt_counter: self.attempt_id.get(),
            registered_channels,
            sealed_channels,
            required_channels: CompilerReadObservationChannelV2::ALL.len(),
            events: self.event_count,
            bytes: self.byte_count,
            failure: self.failure,
            missing_channels,
            unsealed_channels,
            transcript_digest: *transcript.finalize().as_bytes(),
        }
    }

    #[cfg(test)]
    fn channel_event_count(&self, channel: CompilerReadObservationChannelV2) -> u64 {
        self.channels[channel.index()].next_sequence
    }

    fn check_healthy(&self) -> Result<(), CompilerReadObservationFailureV2> {
        self.failure.map_or(Ok(()), Err)
    }

    fn poison<T>(
        &mut self,
        failure: CompilerReadObservationFailureV2,
    ) -> Result<T, CompilerReadObservationFailureV2> {
        let first_failure = *self.failure.get_or_insert(failure);
        Err(first_failure)
    }
}

fn class_matches_channel(
    class: CompilerReadObservationEventClassV2,
    channel: CompilerReadObservationChannelV2,
) -> bool {
    use CompilerReadObservationChannelV2 as Channel;
    use CompilerReadObservationEventClassV2 as Class;
    match channel {
        Channel::EditorOverlay => class == Class::EditorBuffer,
        Channel::RaVfsLoader | Channel::AuthorityFilesystem => {
            matches!(class, Class::PresentFile | Class::AbsentPath)
        }
        Channel::RustModuleResolver => matches!(
            class,
            Class::PresentFile | Class::AbsentPath | Class::ModuleResolution
        ),
        Channel::DirectoryEnumeration => class == Class::DirectoryListing,
        Channel::CargoProjectModel => {
            matches!(
                class,
                Class::CargoProject
                    | Class::PresentFile
                    | Class::AbsentPath
                    | Class::DirectoryListing
            )
        }
        Channel::Environment => class == Class::EnvironmentValue,
        Channel::ProcessTree => class == Class::ChildProcess,
        Channel::ToolchainSysroot => matches!(
            class,
            Class::ToolchainInput
                | Class::PresentFile
                | Class::AbsentPath
                | Class::DirectoryListing
                | Class::ChildProcess
        ),
        Channel::GeneratedOutputs => class == Class::GeneratedOutput,
        Channel::ExternalDependencies => {
            matches!(class, Class::ExternalInput | Class::AbsentPath)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn recorder() -> CompilerReadObservationRecorderV2 {
        CompilerReadObservationRecorderV2::new(
            crate::compiler_attempt_v2::CompilationAttemptId::mint().expect("attempt identity"),
        )
    }

    #[test]
    fn recorder_uses_the_owner_minted_attempt_counter() {
        let attempt =
            crate::compiler_attempt_v2::CompilationAttemptId::mint().expect("attempt identity");
        let recorder = CompilerReadObservationRecorderV2::new(attempt);
        assert_eq!(recorder.report().attempt_counter(), attempt.get());
    }

    #[test]
    fn observation_recorder_seals_only_registered_channel_events_and_stays_partial() {
        let mut recorder = recorder();
        let producer = recorder
            .register(CompilerReadObservationChannelV2::EditorOverlay)
            .expect("editor buffer producer");
        recorder
            .observe_editor_buffer(&producer, 0, "src/lib.rs", b"pub fn value() {}\n")
            .expect("first selected buffer");
        recorder
            .observe_editor_buffer(&producer, 1, "src/main.rs", b"fn main() {}\n")
            .expect("second selected buffer");
        recorder.seal(&producer, 2).expect("producer seal");

        let report = recorder.report();
        assert_eq!(report.events(), 2);
        assert_eq!(report.registered_channels(), 1);
        assert_eq!(report.sealed_channels(), 1);
        assert_eq!(report.required_channels(), 11);
        assert!(!report.all_required_producers_sealed());
        assert!(
            report
                .missing_channel_labels()
                .contains(&"rust_module_resolver")
        );
        assert!(report.missing_channel_labels().contains(&"process_tree"));
    }

    #[test]
    fn stale_read_observation_producer_is_rejected_by_attempt_fence() {
        let mut first = recorder();
        let producer = first
            .register(CompilerReadObservationChannelV2::EditorOverlay)
            .expect("producer");
        let second = recorder();
        let mut second = second;
        assert_eq!(
            second.observe_editor_buffer(&producer, 0, "src/lib.rs", b"fn main() {}"),
            Err(CompilerReadObservationFailureV2::StaleAttemptOrProducer)
        );
        assert_eq!(
            second.report().failure(),
            Some(CompilerReadObservationFailureV2::StaleAttemptOrProducer)
        );
    }

    #[test]
    fn unsupported_path_poisoning_prevents_a_channel_seal() {
        let mut recorder = recorder();
        let producer = recorder
            .register(CompilerReadObservationChannelV2::RustModuleResolver)
            .expect("module resolver producer");
        assert_eq!(
            recorder.observe_path_event(
                &producer,
                0,
                CompilerReadObservationEventClassV2::AbsentPath,
                "src/../outside.rs",
                *blake3::hash(b"absent").as_bytes(),
                0,
            ),
            Err(CompilerReadObservationFailureV2::UnsupportedPath)
        );
        assert_eq!(
            recorder.seal(&producer, 0),
            Err(CompilerReadObservationFailureV2::UnsupportedPath)
        );
    }

    #[test]
    fn observation_failure_keeps_the_first_cause() {
        let mut recorder = recorder();
        let producer = recorder
            .register(CompilerReadObservationChannelV2::EditorOverlay)
            .expect("editor producer");
        assert_eq!(
            recorder.observe_editor_buffer(&producer, 1, "src/lib.rs", b"fn f() {}"),
            Err(CompilerReadObservationFailureV2::SequenceGap)
        );
        assert_eq!(
            recorder.observe_editor_buffer(&producer, 0, "src/../bad.rs", b"fn f() {}"),
            Err(CompilerReadObservationFailureV2::SequenceGap)
        );
        assert_eq!(
            recorder.report().failure(),
            Some(CompilerReadObservationFailureV2::SequenceGap)
        );
    }

    #[test]
    fn independent_oracle_detects_an_omitted_negative_module_lookup() {
        let mut recorder = recorder();
        let producer = recorder
            .register(CompilerReadObservationChannelV2::RustModuleResolver)
            .expect("module resolver producer");
        let positive = *blake3::hash(b"contents of src/lib.rs").as_bytes();
        recorder
            .observe_path_event(
                &producer,
                0,
                CompilerReadObservationEventClassV2::ModuleResolution,
                "src/lib.rs",
                positive,
                0,
            )
            .expect("observed positive module resolution");
        recorder
            .seal(&producer, 1)
            .expect("producer terminal count");

        // Independent fixture oracle: `mod optional;` caused both the present
        // parent source and this absent candidate to be consulted. The fake
        // adapter intentionally omits the negative candidate but seals its own
        // internally consistent count, which cannot detect the omission alone.
        let independently_expected = [
            (
                CompilerReadObservationEventClassV2::ModuleResolution,
                "src/lib.rs",
            ),
            (
                CompilerReadObservationEventClassV2::AbsentPath,
                "src/optional.rs",
            ),
        ];
        assert_eq!(independently_expected.len(), 2);
        assert_eq!(
            recorder.channel_event_count(CompilerReadObservationChannelV2::RustModuleResolver),
            1
        );
        assert_ne!(
            recorder.channel_event_count(CompilerReadObservationChannelV2::RustModuleResolver),
            u64::try_from(independently_expected.len()).expect("small fixture count")
        );
    }

    #[test]
    fn opaque_ra_vfs_and_hir_module_events_remain_diagnostic_and_sequenced() {
        let mut recorder = CompilerReadObservationRecorderV2::new().expect("attempt id");
        let vfs = recorder
            .register(CompilerReadObservationChannelV2::RaVfsLoader)
            .expect("RA VFS producer");
        let module = recorder
            .register(CompilerReadObservationChannelV2::RustModuleResolver)
            .expect("module resolver producer");
        recorder
            .observe_opaque_path_event(
                &vfs,
                0,
                CompilerReadObservationEventClassV2::PresentFile,
                *blake3::hash(b"absolute RA path").as_bytes(),
                *blake3::hash(b"VFS bytes").as_bytes(),
                8,
            )
            .expect("loaded VFS file");
        recorder
            .observe_opaque_path_event(
                &module,
                0,
                CompilerReadObservationEventClassV2::ModuleResolution,
                *blake3::hash(b"declaring file identity").as_bytes(),
                *blake3::hash(b"absent.rs").as_bytes(),
                9,
            )
            .expect("HIR-reported unresolved candidate");
        recorder.seal(&vfs, 1).expect("VFS source count");
        recorder.seal(&module, 1).expect("HIR source count");

        let report = recorder.report();
        assert_eq!(report.events(), 2);
        assert_eq!(report.sealed_channels(), 2);
        assert_eq!(report.required_channels(), 11);
        assert!(!report.all_required_producers_sealed());
        assert_eq!(report.failure(), None);
    }

    #[test]
    fn child_event_loss_disagrees_with_independent_child_terminal_count() {
        let mut recorder = recorder();
        let producer = recorder
            .register(CompilerReadObservationChannelV2::ProcessTree)
            .expect("process-tree producer");
        let child_start = *blake3::hash(b"cargo child start").as_bytes();
        recorder
            .observe_nonpath_event(
                &producer,
                0,
                CompilerReadObservationEventClassV2::ChildProcess,
                child_start,
                0,
            )
            .expect("child start event");
        // The process supervisor independently reports both start and exit.
        // Losing the exit event must poison the broker at the seal boundary.
        assert_eq!(
            recorder.seal(&producer, 2),
            Err(CompilerReadObservationFailureV2::FinalCountMismatch)
        );
        assert_eq!(
            recorder.report().failure(),
            Some(CompilerReadObservationFailureV2::FinalCountMismatch)
        );
    }
}
