[package]
name = "backend-extension-trustfall"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
backend-version = { path = "../../crates/version" }
backend-flow = { path = "../../crates/flow" }
backend-semantic = { path = "../../crates/semantic" }

[lints]
workspace = true

[lib]
path = "src/lib.rs"
