[package]
name = "nudox-object"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
derive_more.workspace = true
nudox-id = { path = "../nudox-id" }
nudox-schema = { path = "../nudox-schema" }
thiserror.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
