[package]
name = "wave-application-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nudox-compile-registry = { path = "../../../compiler/crates/nudox-compile-registry" }
nudox-compile-vocab = { path = "../../../compiler/crates/nudox-compile-vocab" }
nudox-observe = { path = "../../../../crates/nudox-observe" }

[lints]
workspace = true
