[package]
name = "nudox-object-pack"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
[dependencies]
nudox-id = { path = "../nudox-id" }
nudox-object = { path = "../nudox-object" }
nudox-schema = { path = "../nudox-schema" }
thiserror.workspace = true
zerocopy.workspace = true
[dev-dependencies]
allocation-counter.workspace = true
[lints]
workspace = true
