[package]
name = "nudox-observability-adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.nudox]
role = "adapter"

[dependencies]
nudox-hydration = { path = "../nudox-hydration" }
nudox-observe = { path = "../nudox-observe" }
nudox-root = { path = "../nudox-root" }
nudox-runtime = { path = "../nudox-runtime" }
nudox-store-memory = { path = "../nudox-store-memory" }
nudox-workflow = { path = "../nudox-workflow" }
opentelemetry.workspace = true
opentelemetry-appender-tracing.workspace = true
opentelemetry_sdk.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
opentelemetry_sdk = { workspace = true, features = ["testing"] }

[lints.rust]
unsafe_code = "forbid"
missing_docs = "deny"

[lints.clippy]
all = "deny"
pedantic = "deny"
