[package]
name = "backend-present"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
backend-client = { path = "../client" }
backend-library = { path = "../library" }
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true

[lib]
path = "lib.rs"
