[package]
name = "nudox-adaptive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"

[dependencies]
nudox-id = { path = "../nudox-id" }
nudox-index-vocab = { path = "../nudox-index-vocab" }
strum.workspace = true
