[package]
name = "nudox-ir"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bimap = { workspace = true }
bon = { workspace = true }
elsa = { workspace = true }
ouroboros = { workspace = true }
papaya = { workspace = true }
parking_lot = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
triomphe = { workspace = true }

[dev-dependencies]
itertools = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
vfs = { workspace = true, features = ["async-vfs"] }
